In [76]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score,make_scorer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.model_selection import train_test_split,RandomizedSearchCV,cross_val_score
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from imblearn.combine import SMOTEENN
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE,ADASYN
from collections import Counter
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
import optuna
import joblib

In [63]:
model_dt=DecisionTreeClassifier()
sc=StandardScaler()
model_dt2=DecisionTreeClassifier()
mms=MinMaxScaler()
model_dt3=DecisionTreeClassifier()
sm=SMOTEENN()
model_dt_smotenn=DecisionTreeClassifier()
model_rf_smoteenn=RandomForestClassifier(n_estimators=500)
model_xgb=XGBClassifier(random_state=42)
model_xgb_smoteenn=XGBClassifier(random_state=42)
smote=SMOTE(random_state=42)
model_xgb_smote=XGBClassifier(random_state=42)
adasyn=ADASYN(random_state=42)
model_xgb_adasyn=XGBClassifier(random_state=42)
model_rf=RandomForestClassifier(
    class_weight='balanced',
    random_state=42,
    n_estimators=300,
    max_depth=6
)
model_cat=CatBoostClassifier(
    auto_class_weights='Balanced',
    verbose=0,
    random_state=42
)
model_ada_weighted=AdaBoostClassifier(
    n_estimators=50,
    random_state=42
)

In [3]:
df=pd.read_csv('../Data/Customer-Churn.csv')

In [4]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

## **Churn Rate**: 26.53%

- Which means, 26.53% of the customers churn out of this telecom company

In [6]:
y=df['Churn']

x=df.drop(columns=['customerID','Churn'])

print("Shape Of X:",x.shape)
print("Shape of Y : ",y.shape)

Shape Of X: (7043, 19)
Shape of Y :  (7043,)

## Train Test Split

In [7]:
x=pd.get_dummies(x,drop_first=True)
y=df['Churn'].map({'No':0,'Yes':1})

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Model Building

In [9]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [10]:
y_pred_dt=model_dt.predict(x_test)

In [11]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84      1013
           1       0.59      0.51      0.55       396

    accuracy                           0.76      1409
   macro avg       0.70      0.69      0.69      1409
weighted avg       0.75      0.76      0.76      1409

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## Initial Insights

- Base model has a accuracy of 76% which is not reliable because of the imbalanced dataset
- TotalCharges needs to be a float/int type (Data Cleaning)
- Need to perform Feature Scaling

## Data Cleaning

In [13]:
telco_data=df.copy()

In [14]:
telco_data.TotalCharges=pd.to_numeric(telco_data.TotalCharges,errors='coerce')

In [15]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [16]:
telco_data.loc[telco_data['TotalCharges'].isnull()==True]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [17]:
telco_data.dropna(how='any',inplace=True)

In [18]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [19]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [20]:
telco_data.tenure.max()

72

In [21]:
import pandas as pd

bins=[0,12,24,36,48,60,72]

labels=['1-12','13-24','25-36','37-48','49-60','61-72']

telco_data['tenure_bin']=pd.cut(telco_data['tenure'],labels=labels,bins=bins,include_lowest=True)

print(telco_data[['tenure','tenure_bin']].head(10))
print(telco_data['tenure_bin'].value_counts().sort_index())

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
5       8       1-12
6      22      13-24
7      10       1-12
8      28      25-36
9      62      61-72
tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [22]:
telco_data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_bin
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [23]:
y=telco_data['Churn']

x=telco_data.drop(columns=['customerID','Churn','tenure'])

print("Shape of X :",x.shape)
print("Shape of y :",y.shape)

Shape of X : (7032, 19)
Shape of y : (7032,)

In [24]:
x

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,tenure_bin
0,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1-12
1,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,25-36
2,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1-12
3,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,37-48
4,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,13-24
7039,Female,0,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,61-72
7040,Female,0,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,1-12
7041,Male,1,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,1-12
7042,Male,0,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,61-72

In [25]:
x=pd.get_dummies(x,drop_first=True)
y=telco_data['Churn'].map({'No':0,"Yes":1})

In [26]:
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_bin_13-24,tenure_bin_25-36,tenure_bin_37-48,tenure_bin_49-60,tenure_bin_61-72
0,0,29.85,29.85,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
1,0,56.95,1889.50,True,False,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,0,53.85,108.15,True,False,False,True,False,False,False,...,False,True,False,False,True,False,False,False,False,False
3,0,42.30,1840.75,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,False,False,False,True,False,False,True,...,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,84.80,1990.50,True,True,True,True,False,True,False,...,False,True,False,False,True,True,False,False,False,False
7039,0,103.20,7362.90,False,True,True,True,False,True,True,...,False,True,True,False,False,False,False,False,False,True
7040,0,29.60,346.45,False,True,True,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
7041,1,74.40,306.60,True,True,False,True,False,True,True,...,False,True,False,False,True,False,False,False,False,False
7042,0,105.65,6844.50,True,False,False,True,False,False,True,...,True,True,False,False,False,False,False,False,False,True

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Feature Scaling

In [28]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [29]:
model_dt2.fit(x_train,y_train)
y_pred_dt2=model_dt2.predict(x_test)

In [30]:
print(classification_report(y_test,y_pred_dt2))

              precision    recall  f1-score   support

           0       0.80      0.79      0.80      1003
           1       0.49      0.50      0.50       404

    accuracy                           0.71      1407
   macro avg       0.64      0.65      0.65      1407
weighted avg       0.71      0.71      0.71      1407

## Feature Scaling - MinMaxScaler

In [31]:
x_train_mms=mms.fit_transform(x_train)
x_test_mms=mms.transform(x_test)

In [32]:
model_dt3.fit(x_train_mms,y_train)

y_pred_dt3=model_dt3.predict(x_test_mms)

In [33]:
print(classification_report(y_test,y_pred_dt3))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80      1003
           1       0.51      0.50      0.51       404

    accuracy                           0.72      1407
   macro avg       0.65      0.65      0.65      1407
weighted avg       0.72      0.72      0.72      1407

## SMOTEENN () [UpSampling + ENN)

In [34]:
x_train_resampled,y_train_resampled=sm.fit_resample(x_train,y_train)

In [35]:
model_dt_smotenn.fit(x_train_resampled,y_train_resampled)

y_pred_dt_smoteen=model_dt_smotenn.predict(x_test)

In [36]:
print(classification_report(y_test,y_pred_dt_smoteen))

              precision    recall  f1-score   support

           0       0.89      0.69      0.78      1003
           1       0.50      0.78      0.61       404

    accuracy                           0.72      1407
   macro avg       0.70      0.74      0.70      1407
weighted avg       0.78      0.72      0.73      1407

In [37]:
model_rf_smoteenn.fit(x_train_resampled,y_train_resampled)
y_pred_rf_smoteenn=model_rf_smoteenn.predict(x_test)

In [38]:
print(classification_report(y_test,y_pred_rf_smoteenn))

              precision    recall  f1-score   support

           0       0.91      0.68      0.78      1003
           1       0.51      0.82      0.63       404

    accuracy                           0.72      1407
   macro avg       0.71      0.75      0.71      1407
weighted avg       0.79      0.72      0.74      1407

## XGBoost without SMOTEENN

In [39]:
model_xgb.fit(x_train,y_train)

y_pred_xgb=model_xgb.predict(x_test)

In [40]:
print(classification_report(y_test,y_pred_xgb))

              precision    recall  f1-score   support

           0       0.82      0.87      0.84      1003
           1       0.61      0.53      0.57       404

    accuracy                           0.77      1407
   macro avg       0.72      0.70      0.70      1407
weighted avg       0.76      0.77      0.76      1407

## XGBoost with SMOTE

In [41]:
print("Before SMOTE :",Counter(y_train))

x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)

print("After SMOTE :",Counter(y_train_smote))

model_xgb_smote.fit(x_train_smote,y_train_smote)

y_pred_xgb_smote=model_xgb_smote.predict(x_test)

Before SMOTE : Counter({0: 4160, 1: 1465})
After SMOTE : Counter({1: 4160, 0: 4160})

In [42]:
print(classification_report(y_test,y_pred_xgb_smote))

              precision    recall  f1-score   support

           0       0.84      0.85      0.85      1003
           1       0.62      0.61      0.61       404

    accuracy                           0.78      1407
   macro avg       0.73      0.73      0.73      1407
weighted avg       0.78      0.78      0.78      1407

In [43]:
print("Before ADASYN :",Counter(y_train))

x_train_adasyn,y_train_adasyn=adasyn.fit_resample(x_train,y_train)

print("After ADASYN :",Counter(y_train_adasyn))

model_xgb_adasyn.fit(x_train_adasyn,y_train_adasyn)

y_pred_xgb_adasyn=model_xgb_adasyn.predict(x_test)

print("Accuracy : ",accuracy_score(y_test,y_pred_xgb_adasyn))
print("Classification Report : \n",classification_report(y_test,y_pred_xgb_adasyn))
print("Confusion Matrix :\n",confusion_matrix(y_test,y_pred_xgb_adasyn))

Before ADASYN : Counter({0: 4160, 1: 1465})
After ADASYN : Counter({0: 4160, 1: 4035})
Accuracy :  0.783226723525231
Classification Report :
               precision    recall  f1-score   support

           0       0.84      0.85      0.85      1003
           1       0.63      0.61      0.62       404

    accuracy                           0.78      1407
   macro avg       0.74      0.73      0.73      1407
weighted avg       0.78      0.78      0.78      1407

Confusion Matrix :
 [[857 146]
 [159 245]]

In [57]:
scale_pos_weight=(y_train==0).sum()/(y_train==1).sum()
print(f"Scale_pos_weight : {scale_pos_weight}")

model_xgb_weighted=XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'
)

model_xgb_weighted.fit(x_train,y_train)
y_pred_weighted=model_xgb_weighted.predict(x_test)

print("Accuracy :",accuracy_score(y_test,y_pred_weighted))
print("\nClassification Report :\n",classification_report(y_test,y_pred_weighted))
print("\n Confusion Matrix :\n",confusion_matrix(y_test,y_pred_weighted))

Scale_pos_weight : 2.839590443686007
Accuracy : 0.7604832977967306

Classification Report :
               precision    recall  f1-score   support

           0       0.86      0.79      0.83      1003
           1       0.57      0.68      0.62       404

    accuracy                           0.76      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.78      0.76      0.77      1407


 Confusion Matrix :
 [[797 206]
 [131 273]]

In [69]:
negative_count=(y_train==0).sum()
positive_count=(y_train==1).sum()
weighted_positive=negative_count/positive_count
print(f"Negative Class Count : ",negative_count)
print(f"Positive Class Count : ",positive_count)
print(f"Weighted for positive Count ",weighted_positive)

sample_weight=np.where(y_train==1,weighted_positive,1.0)

model_ada_weighted.fit(x_train,y_train,sample_weight=sample_weight)

y_pred_ada_weighted=model_ada_weighted.predict(x_test)

print("Adaboost With Sample Weighting Accuracy ",accuracy_score(y_test,y_pred_ada_weighted))
print("\nClassification Report:\n",classification_report(y_test,y_pred_ada_weighted))
print("\n Confusion Matrix:\n",confusion_matrix(y_test,y_pred_ada_weighted))

Negative Class Count :  4160
Positive Class Count :  1465
Weighted for positive Count  2.839590443686007
Adaboost With Sample Weighting Accuracy  0.738450604122246

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.70      0.79      1003
           1       0.53      0.82      0.64       404

    accuracy                           0.74      1407
   macro avg       0.72      0.76      0.72      1407
weighted avg       0.80      0.74      0.75      1407


 Confusion Matrix:
 [[706 297]
 [ 71 333]]

In [71]:
param_grid={
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight] 
    
}
xgb=XGBClassifier(random_state=42,eval_metric='logloss')

search=RandomizedSearchCV(
    xgb,
    param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',
    random_state=42,
    n_jobs=-1
)
search.fit(x_train,y_train)

print("Best Parameters :",search.best_params_)
print("Best CV F1 Score :",search.best_score_)

best_model=search.best_estimator_
y_pred_best=best_model.predict(x_test)
print("\n Test Classification Report :\n",classification_report(y_test,y_pred_best))

Best Parameters : {'subsample': 0.8, 'scale_pos_weight': 2.839590443686007, 'n_estimators': 400, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.01, 'gamma': 0, 'colsample_bytree': 0.7}
Best CV F1 Score : 0.6303995740741408

 Test Classification Report :
               precision    recall  f1-score   support

           0       0.90      0.71      0.80      1003
           1       0.53      0.81      0.64       404

    accuracy                           0.74      1407
   macro avg       0.72      0.76      0.72      1407
weighted avg       0.80      0.74      0.75      1407

In [72]:
joblib.dump(best_model,'../Models/best_xgboost_churn_model.pkl')
print("Best Model succesfully saved as best_xgboost_churn_model.pkl")

Best Model succesfully saved as best_xgboost_churn_model.pkl

## Trying out few more techniques

In [44]:
model_rf.fit(x_train,y_train)
y_pred_rf=model_rf.predict(x_test)
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.90      0.69      0.78      1003
           1       0.51      0.80      0.62       404

    accuracy                           0.72      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.72      0.73      1407

In [49]:
model_cat.fit(x_train,y_train)
y_pred_cat=model_cat.predict(x_test)
print(classification_report(y_test,y_pred_cat))

              precision    recall  f1-score   support

           0       0.88      0.75      0.81      1003
           1       0.54      0.75      0.63       404

    accuracy                           0.75      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.75      0.76      1407

In [74]:
model_lgb=LGBMClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42
)
model_lgb.fit(x_train,y_train)
y_pred_lgb=model_lgb.predict(x_test)
print(classification_report(y_test,y_pred_lgb))

              precision    recall  f1-score   support

           0       0.89      0.75      0.81      1003
           1       0.55      0.77      0.64       404

    accuracy                           0.75      1407
   macro avg       0.72      0.76      0.73      1407
weighted avg       0.79      0.75      0.76      1407

## **Optuna fine tuning**

In [78]:
def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  # L1 regularization
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), # L2 regularization
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'
    }
    model=XGBClassifier(**params)

    f1_scorer=make_scorer(f1_score,average='binary',pos_label=1)
    score=cross_val_score(model,x_train,y_train,cv=5,scoring=f1_scorer,n_jobs=-1).mean()

    return score
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)

print("Best Parameters : ",study.best_params)
print("Best CV F1 Score : ",study.best_value)

best_model_optuna=XGBClassifier(**study.best_params)
best_model_optuna.fit(x_train,y_train)
y_pred_optuna=best_model_optuna.predict(x_test)
print(classification_report(y_test,y_pred_optuna))

[I 2026-07-04 01:42:38,612] A new study created in memory with name: no-name-e3b71810-d8a7-403a-a957-a5c9ed0fff71
[I 2026-07-04 01:42:40,255] Trial 0 finished with value: 0.5660326680677066 and parameters: {'max_depth': 6, 'learning_rate': 0.24765382274333614, 'n_estimators': 838, 'subsample': 0.6297403143953141, 'colsample_bytree': 0.6595640913101503, 'min_child_weight': 7, 'gamma': 0.48986392846064875, 'reg_alpha': 0.9153000362388155, 'reg_lambda': 1.7294692474844489, 'scale_pos_weight': 2.839590443686007}. Best is trial 0 with value: 0.5660326680677066.
[I 2026-07-04 01:42:42,051] Trial 1 finished with value: 0.5471843433791479 and parameters: {'max_depth': 8, 'learning_rate': 0.08153355937028009, 'n_estimators': 963, 'subsample': 0.8893387094005796, 'colsample_bytree': 0.8439647385563188, 'min_child_weight': 9, 'gamma': 0.23376315172882633, 'reg_alpha': 0.9233427697668368, 'reg_lambda': 1.7272212013359125, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.5660326680677066.
[I 2026-07-04 01:42:42,928] Trial 2 finished with value: 0.5634454251425065 and parameters: {'max_depth': 5, 'learning_rate': 0.0763535973211205, 'n_estimators': 406, 'subsample': 0.6637219623032498, 'colsample_bytree': 0.926363380524291, 'min_child_weight': 9, 'gamma': 0.19911943223209705, 'reg_alpha': 0.9501900600895146, 'reg_lambda': 1.1612578215408211, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.5660326680677066.
[I 2026-07-04 01:42:44,678] Trial 3 finished with value: 0.6103358529403845 and parameters: {'max_depth': 9, 'learning_rate': 0.019044794882047498, 'n_estimators': 691, 'subsample': 0.9364283098891333, 'colsample_bytree': 0.8526429294275786, 'min_child_weight': 8, 'gamma': 0.08653773794788105, 'reg_alpha': 0.022608083781233912, 'reg_lambda': 1.308762866632753, 'scale_pos_weight': 2.839590443686007}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:45,329] Trial 4 finished with value: 0.5779530921219661 and parameters: {'max_depth': 10, 'learning_rate': 0.2453682761022505, 'n_estimators': 178, 'subsample': 0.7761236648337454, 'colsample_bytree': 0.7582191537221528, 'min_child_weight': 9, 'gamma': 0.26788534701083716, 'reg_alpha': 0.344448991974864, 'reg_lambda': 0.8015908574936734, 'scale_pos_weight': 2.839590443686007}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:46,475] Trial 5 finished with value: 0.5954782705741893 and parameters: {'max_depth': 4, 'learning_rate': 0.14675430699510167, 'n_estimators': 640, 'subsample': 0.8162279491589333, 'colsample_bytree': 0.7908622468717461, 'min_child_weight': 3, 'gamma': 0.26161218570696165, 'reg_alpha': 0.9526785416565647, 'reg_lambda': 1.6833511294113768, 'scale_pos_weight': 2.839590443686007}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:47,963] Trial 6 finished with value: 0.5770934469291924 and parameters: {'max_depth': 5, 'learning_rate': 0.011135071593815313, 'n_estimators': 721, 'subsample': 0.9567564950370447, 'colsample_bytree': 0.9902241435276039, 'min_child_weight': 1, 'gamma': 0.08926284991575517, 'reg_alpha': 0.8835149227681423, 'reg_lambda': 0.5961687621029721, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:49,134] Trial 7 finished with value: 0.5514586397490575 and parameters: {'max_depth': 10, 'learning_rate': 0.20349582904667818, 'n_estimators': 561, 'subsample': 0.7159422302875059, 'colsample_bytree': 0.709022962998488, 'min_child_weight': 1, 'gamma': 0.41086823947247897, 'reg_alpha': 0.3171579663806664, 'reg_lambda': 0.5279935076411995, 'scale_pos_weight': 2.839590443686007}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:49,932] Trial 8 finished with value: 0.6058975927670817 and parameters: {'max_depth': 3, 'learning_rate': 0.1375707622636665, 'n_estimators': 457, 'subsample': 0.9751869551981783, 'colsample_bytree': 0.6638748201838587, 'min_child_weight': 3, 'gamma': 0.03588807629541202, 'reg_alpha': 0.27390638317066063, 'reg_lambda': 0.029726469182665527, 'scale_pos_weight': 2.839590443686007}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:50,779] Trial 9 finished with value: 0.5700141195166232 and parameters: {'max_depth': 9, 'learning_rate': 0.018441413712343244, 'n_estimators': 229, 'subsample': 0.6986820647471449, 'colsample_bytree': 0.7298941440837479, 'min_child_weight': 3, 'gamma': 0.3598446787782062, 'reg_alpha': 0.6738128268245331, 'reg_lambda': 0.9516764511404041, 'scale_pos_weight': 1}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:52,747] Trial 10 finished with value: 0.60144462989895 and parameters: {'max_depth': 8, 'learning_rate': 0.033000383652844044, 'n_estimators': 787, 'subsample': 0.8888122181127704, 'colsample_bytree': 0.8656230165410826, 'min_child_weight': 6, 'gamma': 0.11602521862228832, 'reg_alpha': 0.003168974341651705, 'reg_lambda': 1.3545842949073998, 'scale_pos_weight': 2.839590443686007}. Best is trial 3 with value: 0.6103358529403845.
[I 2026-07-04 01:42:53,446] Trial 11 finished with value: 0.6237456158481202 and parameters: {'max_depth': 3, 'learning_rate': 0.03717720798938069, 'n_estimators': 430, 'subsample': 0.9987712262566768, 'colsample_bytree': 0.6807845443502348, 'min_child_weight': 4, 'gamma': 0.0016857433734748517, 'reg_alpha': 0.02066660946247371, 'reg_lambda': 0.036190009978186666, 'scale_pos_weight': 2.839590443686007}. Best is trial 11 with value: 0.6237456158481202.
[I 2026-07-04 01:42:54,365] Trial 12 finished with value: 0.6157987221164285 and parameters: {'max_depth': 7, 'learning_rate': 0.031580717810388695, 'n_estimators': 363, 'subsample': 0.9130099131375795, 'colsample_bytree': 0.6013371793373713, 'min_child_weight': 7, 'gamma': 0.01566142665097949, 'reg_alpha': 0.06308768235368958, 'reg_lambda': 0.05960193127030211, 'scale_pos_weight': 2.839590443686007}. Best is trial 11 with value: 0.6237456158481202.
[I 2026-07-04 01:42:55,260] Trial 13 finished with value: 0.6096280606229172 and parameters: {'max_depth': 7, 'learning_rate': 0.039569373431234386, 'n_estimators': 327, 'subsample': 0.8834246917842706, 'colsample_bytree': 0.6101515782078707, 'min_child_weight': 5, 'gamma': 0.0008650239170498215, 'reg_alpha': 0.1763038816806753, 'reg_lambda': 0.009718166393977445, 'scale_pos_weight': 2.839590443686007}. Best is trial 11 with value: 0.6237456158481202.
[I 2026-07-04 01:42:55,646] Trial 14 finished with value: 0.6285237148974578 and parameters: {'max_depth': 3, 'learning_rate': 0.03197484073626387, 'n_estimators': 104, 'subsample': 0.9810469805621668, 'colsample_bytree': 0.6130421260223367, 'min_child_weight': 5, 'gamma': 0.14497600286736795, 'reg_alpha': 0.5336248230550522, 'reg_lambda': 0.35598435277694185, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:42:56,029] Trial 15 finished with value: 0.6283527071959297 and parameters: {'max_depth': 3, 'learning_rate': 0.05319087011193726, 'n_estimators': 153, 'subsample': 0.9858781165314334, 'colsample_bytree': 0.6878633128651056, 'min_child_weight': 5, 'gamma': 0.1609019907219262, 'reg_alpha': 0.5253115420507704, 'reg_lambda': 0.35533726800491217, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:42:56,491] Trial 16 finished with value: 0.6284586287925971 and parameters: {'max_depth': 4, 'learning_rate': 0.05944683447005423, 'n_estimators': 138, 'subsample': 0.829559440674205, 'colsample_bytree': 0.6393765930282056, 'min_child_weight': 5, 'gamma': 0.16968063013118498, 'reg_alpha': 0.54224531625143, 'reg_lambda': 0.3713792639294018, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:42:57,138] Trial 17 finished with value: 0.6196363290360571 and parameters: {'max_depth': 4, 'learning_rate': 0.08131614518701663, 'n_estimators': 261, 'subsample': 0.806989213278229, 'colsample_bytree': 0.6426515620505964, 'min_child_weight': 6, 'gamma': 0.3228918014360117, 'reg_alpha': 0.5989013274648908, 'reg_lambda': 0.38995019204367853, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:42:57,542] Trial 18 finished with value: 0.5327175931175872 and parameters: {'max_depth': 4, 'learning_rate': 0.021054034201955975, 'n_estimators': 109, 'subsample': 0.8543613997039883, 'colsample_bytree': 0.7517886275496535, 'min_child_weight': 4, 'gamma': 0.16271396289844064, 'reg_alpha': 0.7470857610108796, 'reg_lambda': 0.704087857323238, 'scale_pos_weight': 1}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:42:58,267] Trial 19 finished with value: 0.6192113072755642 and parameters: {'max_depth': 5, 'learning_rate': 0.051510374544441885, 'n_estimators': 277, 'subsample': 0.7458634412954686, 'colsample_bytree': 0.6247029255463326, 'min_child_weight': 7, 'gamma': 0.14877595672631835, 'reg_alpha': 0.437806248147997, 'reg_lambda': 0.3611639336381548, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:42:59,565] Trial 20 finished with value: 0.6201421968114824 and parameters: {'max_depth': 6, 'learning_rate': 0.011442282886891086, 'n_estimators': 508, 'subsample': 0.8434039216456987, 'colsample_bytree': 0.8073593312200747, 'min_child_weight': 2, 'gamma': 0.207816201852677, 'reg_alpha': 0.44892093233368624, 'reg_lambda': 0.8834861489076212, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:42:59,936] Trial 21 finished with value: 0.627338680701481 and parameters: {'max_depth': 3, 'learning_rate': 0.05645235137254189, 'n_estimators': 101, 'subsample': 0.9358279985203606, 'colsample_bytree': 0.6964695635011785, 'min_child_weight': 5, 'gamma': 0.16502033241848765, 'reg_alpha': 0.5987978824013199, 'reg_lambda': 0.30008094845504707, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:43:00,384] Trial 22 finished with value: 0.6211358243306963 and parameters: {'max_depth': 3, 'learning_rate': 0.06473338077079907, 'n_estimators': 187, 'subsample': 0.9913757604279658, 'colsample_bytree': 0.6495932648552286, 'min_child_weight': 4, 'gamma': 0.11575555510573785, 'reg_alpha': 0.5470905485230653, 'reg_lambda': 0.27938295514057365, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:43:00,827] Trial 23 finished with value: 0.621637129701169 and parameters: {'max_depth': 4, 'learning_rate': 0.10939810262424786, 'n_estimators': 172, 'subsample': 0.9535118922581586, 'colsample_bytree': 0.7032907616744623, 'min_child_weight': 5, 'gamma': 0.2956962688638488, 'reg_alpha': 0.7594384809880144, 'reg_lambda': 0.5221755992976916, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:43:01,220] Trial 24 finished with value: 0.6274846351410205 and parameters: {'max_depth': 3, 'learning_rate': 0.025333077415070997, 'n_estimators': 100, 'subsample': 0.7653662647900545, 'colsample_bytree': 0.6328939933510529, 'min_child_weight': 6, 'gamma': 0.06643032000866782, 'reg_alpha': 0.4760892665209822, 'reg_lambda': 0.16891743872759898, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:43:01,961] Trial 25 finished with value: 0.6247371884268154 and parameters: {'max_depth': 4, 'learning_rate': 0.04005209016351726, 'n_estimators': 328, 'subsample': 0.9113731852670582, 'colsample_bytree': 0.6777683284526509, 'min_child_weight': 4, 'gamma': 0.21674829992893685, 'reg_alpha': 0.6768458720458135, 'reg_lambda': 0.704763761960918, 'scale_pos_weight': 2.839590443686007}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:43:02,502] Trial 26 finished with value: 0.5735528936433585 and parameters: {'max_depth': 5, 'learning_rate': 0.046571425766176365, 'n_estimators': 216, 'subsample': 0.8416222336685127, 'colsample_bytree': 0.6012691972606975, 'min_child_weight': 5, 'gamma': 0.13630586639343667, 'reg_alpha': 0.5495631254159169, 'reg_lambda': 0.46161232261998797, 'scale_pos_weight': 1}. Best is trial 14 with value: 0.6285237148974578.
[I 2026-07-04 01:43:03,051] Trial 27 finished with value: 0.6325163751958598 and parameters: {'max_depth': 3, 'learning_rate': 0.02474886856052479, 'n_estimators': 280, 'subsample': 0.9615290994390482, 'colsample_bytree': 0.7401918869490528, 'min_child_weight': 10, 'gamma': 0.18246705572126054, 'reg_alpha': 0.3875590564709742, 'reg_lambda': 0.23184949924221615, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:03,689] Trial 28 finished with value: 0.6294020340985529 and parameters: {'max_depth': 4, 'learning_rate': 0.01526860956854681, 'n_estimators': 259, 'subsample': 0.9201391071684076, 'colsample_bytree': 0.7359578157963235, 'min_child_weight': 10, 'gamma': 0.19286450563869703, 'reg_alpha': 0.364518098328463, 'reg_lambda': 0.2345043443282011, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:04,545] Trial 29 finished with value: 0.6247638788906206 and parameters: {'max_depth': 6, 'learning_rate': 0.014524741225567538, 'n_estimators': 291, 'subsample': 0.9632487106372009, 'colsample_bytree': 0.7881036732316526, 'min_child_weight': 10, 'gamma': 0.19301520495036295, 'reg_alpha': 0.3877946071534199, 'reg_lambda': 0.2273140959449505, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:05,685] Trial 30 finished with value: 0.6209512067989864 and parameters: {'max_depth': 5, 'learning_rate': 0.02544563327430672, 'n_estimators': 573, 'subsample': 0.9240779601387922, 'colsample_bytree': 0.7443184350489174, 'min_child_weight': 10, 'gamma': 0.3773352993637711, 'reg_alpha': 0.24355959368143376, 'reg_lambda': 1.106286582679266, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:06,293] Trial 31 finished with value: 0.6268629916756235 and parameters: {'max_depth': 4, 'learning_rate': 0.014350719292550067, 'n_estimators': 230, 'subsample': 0.8728840151854369, 'colsample_bytree': 0.7211908183654944, 'min_child_weight': 8, 'gamma': 0.47635002959914274, 'reg_alpha': 0.39070946571551435, 'reg_lambda': 0.18869204369917625, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:07,707] Trial 32 finished with value: 0.6211375911616732 and parameters: {'max_depth': 3, 'learning_rate': 0.027345619354852437, 'n_estimators': 954, 'subsample': 0.9047176252726, 'colsample_bytree': 0.7678222420963445, 'min_child_weight': 10, 'gamma': 0.23978051806808828, 'reg_alpha': 0.19596649704104518, 'reg_lambda': 0.2058934564128975, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:08,513] Trial 33 finished with value: 0.6294347064264869 and parameters: {'max_depth': 4, 'learning_rate': 0.014397793356064751, 'n_estimators': 379, 'subsample': 0.9431974934387871, 'colsample_bytree': 0.6608121120208349, 'min_child_weight': 9, 'gamma': 0.20357887900892227, 'reg_alpha': 0.38783703375609146, 'reg_lambda': 1.9557541587362075, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:09,304] Trial 34 finished with value: 0.5789150160769998 and parameters: {'max_depth': 3, 'learning_rate': 0.0150802384337825, 'n_estimators': 386, 'subsample': 0.9448542784233573, 'colsample_bytree': 0.8098690927638744, 'min_child_weight': 9, 'gamma': 0.2256955341965889, 'reg_alpha': 0.3926272808603945, 'reg_lambda': 1.5761748081226443, 'scale_pos_weight': 1}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:10,348] Trial 35 finished with value: 0.6246331003510738 and parameters: {'max_depth': 5, 'learning_rate': 0.02071858076063333, 'n_estimators': 470, 'subsample': 0.6314049046612393, 'colsample_bytree': 0.6637223754913331, 'min_child_weight': 8, 'gamma': 0.1888536197224447, 'reg_alpha': 0.12387057036078986, 'reg_lambda': 1.909933529806811, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:11,099] Trial 36 finished with value: 0.6318395177951386 and parameters: {'max_depth': 4, 'learning_rate': 0.017093095792146507, 'n_estimators': 330, 'subsample': 0.9686723539123118, 'colsample_bytree': 0.7765976962565332, 'min_child_weight': 9, 'gamma': 0.29600834047153785, 'reg_alpha': 0.30434865280381607, 'reg_lambda': 1.934864665485594, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:12,082] Trial 37 finished with value: 0.5770257820595208 and parameters: {'max_depth': 6, 'learning_rate': 0.010384817548480588, 'n_estimators': 381, 'subsample': 0.9391977635986248, 'colsample_bytree': 0.8290507216880721, 'min_child_weight': 9, 'gamma': 0.2906704932798833, 'reg_alpha': 0.3155461349066874, 'reg_lambda': 1.9814383047505166, 'scale_pos_weight': 1}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:12,761] Trial 38 finished with value: 0.6286244373136749 and parameters: {'max_depth': 4, 'learning_rate': 0.016833251907327797, 'n_estimators': 323, 'subsample': 0.8624184254733532, 'colsample_bytree': 0.8735220938261216, 'min_child_weight': 9, 'gamma': 0.27415717443417653, 'reg_alpha': 0.2510389588841075, 'reg_lambda': 1.8633703551577911, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:13,848] Trial 39 finished with value: 0.6269802061806405 and parameters: {'max_depth': 5, 'learning_rate': 0.013215697388989082, 'n_estimators': 501, 'subsample': 0.9665332841921797, 'colsample_bytree': 0.7719218235008447, 'min_child_weight': 10, 'gamma': 0.3221484691978095, 'reg_alpha': 0.34793982975446536, 'reg_lambda': 1.4322419796784083, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:14,991] Trial 40 finished with value: 0.6225658024189046 and parameters: {'max_depth': 4, 'learning_rate': 0.02246297598148952, 'n_estimators': 608, 'subsample': 0.8971082200999903, 'colsample_bytree': 0.9156304587904602, 'min_child_weight': 8, 'gamma': 0.24895092588884046, 'reg_alpha': 0.282973431954078, 'reg_lambda': 1.749255825056371, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:15,797] Trial 41 finished with value: 0.6250820982924222 and parameters: {'max_depth': 4, 'learning_rate': 0.017295144593110545, 'n_estimators': 328, 'subsample': 0.8738725282580498, 'colsample_bytree': 0.8812792315630029, 'min_child_weight': 9, 'gamma': 0.27659434207590333, 'reg_alpha': 0.2438080812350463, 'reg_lambda': 1.7341588986524668, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:16,517] Trial 42 finished with value: 0.627450539712426 and parameters: {'max_depth': 4, 'learning_rate': 0.016287656627190634, 'n_estimators': 297, 'subsample': 0.9255487295939864, 'colsample_bytree': 0.8967557512172009, 'min_child_weight': 9, 'gamma': 0.3211271639681522, 'reg_alpha': 0.18138156995134597, 'reg_lambda': 1.8579379451742364, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.
[I 2026-07-04 01:43:17,563] Trial 43 finished with value: 0.6254747522602739 and parameters: {'max_depth': 5, 'learning_rate': 0.01150557507975385, 'n_estimators': 418, 'subsample': 0.9548443016524054, 'colsample_bytree': 0.8306230968957797, 'min_child_weight': 10, 'gamma': 0.2651222104875728, 'reg_alpha': 0.34929685970873975, 'reg_lambda': 1.5605741902695212, 'scale_pos_weight': 2.839590443686007}. Best is trial 27 with value: 0.6325163751958598.

Best Parameters :  {'max_depth': 3, 'learning_rate': 0.017015318359525567, 'n_estimators': 627, 'subsample': 0.7295758405266288, 'colsample_bytree': 0.7459064174464416, 'min_child_weight': 10, 'gamma': 0.1362440638789693, 'reg_alpha': 0.9069637219423553, 'reg_lambda': 0.7304480128259802, 'scale_pos_weight': 2.839590443686007}
Best CV F1 Score :  0.6335426701708246
              precision    recall  f1-score   support

           0       0.90      0.71      0.80      1003
           1       0.53      0.81      0.64       404

    accuracy                           0.74      1407
   macro avg       0.72      0.76      0.72      1407
weighted avg       0.80      0.74      0.75      1407

In [79]:
joblib.dump(best_model_optuna,'../Models/Best_optuna_churn_model.pkl')
print("Best Model is saved as Best_optuna_churn_model.pkl")

Best Model is saved as Best_optuna_churn_model.pkl

In [80]:
joblib.dump(model_ada_weighted,'../Models/Ada_boost_churn_model.pkl')
print("Best Model succesfully saved as Ada_boost_churn_model.pkl")

Best Model succesfully saved as Ada_boost_churn_model.pkl