In [202]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import optuna
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,f1_score,make_scorer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.model_selection import train_test_split,RandomizedSearchCV,cross_val_score
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE,ADASYN
from collections import Counter
import warnings

In [199]:
model_dt=DecisionTreeClassifier()
model_dt2=DecisionTreeClassifier()
model_dt3=DecisionTreeClassifier()
model_dt_smotenn=DecisionTreeClassifier()
model_rf_smotenn=RandomForestClassifier(n_estimators=500)
model_xgb=XGBClassifier(random_state=42)
model_xgb_smotenn=XGBClassifier(random_state=42)
model_xgb_smote=XGBClassifier(random_state=42)
model_xgb_adasyn=XGBClassifier(random_state=42)
model_cat=CatBoostClassifier(auto_class_weights='Balanced',verbose=0,random_state=42)
model_rf=RandomForestClassifier(class_weight='balanced',n_estimators=300,max_depth=6,random_state=42)
sc=StandardScaler()
mns=MinMaxScaler()
smenn=SMOTEENN()
smote=SMOTE()
adasyn=ADASYN(random_state=42)
warnings.filterwarnings(action='ignore')

In [109]:
df=pd.read_csv('../data/Customer-Churn.csv')

In [110]:
df.head(5)

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [111]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

## **Churn Rate**: 26.53%

- Which means, 26.53% of the customers churn out of this telecom company

In [112]:
y=df['Churn']
x=df.drop(columns=['customerID','Churn'])


print("Shape of X :",x.shape)
print("Shape of y",y.shape)

Shape of X : (7043, 19)
Shape of y (7043,)

## Train Test Split

In [113]:
x=pd.get_dummies(x,drop_first=True)
y=df['Churn'].map({'No':0,'Yes':1})

In [114]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Model Building

In [115]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [116]:
y_pred_dt=model_dt.predict(x_test)

In [117]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86      1051
           1       0.59      0.54      0.57       358

    accuracy                           0.79      1409
   macro avg       0.72      0.71      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## Initial Insights

- Base model has a accuracy of 76% which is not reliable because of the imbalanced dataset
- TotalCharges needs to be a float/int type (Data Cleaning)
- Need to perform Feature Scaling

## Data Cleaning

In [119]:
telco_data=df.copy()

In [120]:
telco_data.TotalCharges=pd.to_numeric(telco_data.TotalCharges,errors='coerce')

In [121]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [122]:
telco_data.loc[telco_data['TotalCharges'].isnull()==True]

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
488   4472-LVYGI  Female              0  ...          52.55          NaN     No
753   3115-CZMZD    Male              0  ...          20.25          NaN     No
936   5709-LVOEQ  Female              0  ...          80.85          NaN     No
1082  4367-NUYAO    Male              0  ...          25.75          NaN     No
1340  1371-DWPAZ  Female              0  ...          56.05          NaN     No
3331  7644-OMVMY    Male              0  ...          19.85          NaN     No
3826  3213-VVOLG    Male              0  ...          25.35          NaN     No
4380  2520-SGTTA  Female              0  ...          20.00          NaN     No
5218  2923-ARZLG    Male              0  ...          19.70          NaN     No
6670  4075-WKNIU  Female              0  ...          73.35          NaN     No
6754  2775-SEFEE    Male              0  ...          61.90          NaN     No

[11 rows x 21 columns]

In [123]:
telco_data.dropna(how='any',inplace=True)

In [124]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [125]:
telco_data.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95      1889.50     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [126]:
telco_data.tenure.max()

np.int64(72)

In [127]:
bins=[0,12,24,36,48,60,72]
labels=['1-12','13-24','25-36','37-48','49-60','61-72']
telco_data['tenure_bin']=pd.cut(telco_data['tenure'],bins=bins,labels=labels,include_lowest=True)


print(telco_data[['tenure','tenure_bin']].head(10))
print(telco_data['tenure_bin'].value_counts().sort_index())

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
5       8       1-12
6      22      13-24
7      10       1-12
8      28      25-36
9      62      61-72
tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [128]:
telco_data.head(5)

   customerID  gender  SeniorCitizen  ... TotalCharges Churn  tenure_bin
0  7590-VHVEG  Female              0  ...        29.85    No        1-12
1  5575-GNVDE    Male              0  ...      1889.50    No       25-36
2  3668-QPYBK    Male              0  ...       108.15   Yes        1-12
3  7795-CFOCW    Male              0  ...      1840.75    No       37-48
4  9237-HQITU  Female              0  ...       151.65   Yes        1-12

[5 rows x 22 columns]

In [129]:
y=telco_data['Churn']
x=telco_data.drop(columns=['customerID','Churn','tenure'])


print("Shape of x :",x.shape)
print("shape of y:",y.shape)

Shape of x : (7032, 19)
shape of y: (7032,)

In [130]:
x

      gender  SeniorCitizen Partner  ... MonthlyCharges TotalCharges tenure_bin
0     Female              0     Yes  ...          29.85        29.85       1-12
1       Male              0      No  ...          56.95      1889.50      25-36
2       Male              0      No  ...          53.85       108.15       1-12
3       Male              0      No  ...          42.30      1840.75      37-48
4     Female              0      No  ...          70.70       151.65       1-12
...      ...            ...     ...  ...            ...          ...        ...
7038    Male              0     Yes  ...          84.80      1990.50      13-24
7039  Female              0     Yes  ...         103.20      7362.90      61-72
7040  Female              0     Yes  ...          29.60       346.45       1-12
7041    Male              1     Yes  ...          74.40       306.60       1-12
7042    Male              0      No  ...         105.65      6844.50      61-72

[7032 rows x 19 columns]

In [131]:
x=pd.get_dummies(x,drop_first=True)
y=telco_data['Churn'].map({'No':0,'Yes':1})

In [132]:
x

      SeniorCitizen  MonthlyCharges  ...  tenure_bin_49-60  tenure_bin_61-72
0                 0           29.85  ...             False             False
1                 0           56.95  ...             False             False
2                 0           53.85  ...             False             False
3                 0           42.30  ...             False             False
4                 0           70.70  ...             False             False
...             ...             ...  ...               ...               ...
7038              0           84.80  ...             False             False
7039              0          103.20  ...             False              True
7040              0           29.60  ...             False             False
7041              1           74.40  ...             False             False
7042              0          105.65  ...             False              True

[7032 rows x 34 columns]

In [133]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Feature Scaling

In [134]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [135]:
model_dt2.fit(x_train,y_train)

y_pred_dt2=model_dt2.predict(x_test)

In [136]:
print(classification_report(y_test,y_pred_dt2))

              precision    recall  f1-score   support

           0       0.81      0.79      0.80      1017
           1       0.48      0.51      0.49       390

    accuracy                           0.71      1407
   macro avg       0.64      0.65      0.64      1407
weighted avg       0.71      0.71      0.71      1407

## Feature Scaling - MinMaxScaler

In [137]:
x_train_mns=mns.fit_transform(x_train)
x_test_mns=mns.transform(x_test)

In [138]:
model_dt3.fit(x_train_mns,y_train)

y_pred_dt3=model_dt3.predict(x_test_mns)

In [139]:
print(classification_report(y_test,y_pred_dt3))

              precision    recall  f1-score   support

           0       0.81      0.79      0.80      1017
           1       0.48      0.51      0.49       390

    accuracy                           0.71      1407
   macro avg       0.64      0.65      0.65      1407
weighted avg       0.72      0.71      0.71      1407

## SMOTEENN () [UpSampling + ENN)

In [140]:
x_train_resampled,y_train_resampled=smenn.fit_resample(x_train,y_train)

In [141]:
model_dt_smotenn.fit(x_train_resampled,y_train_resampled)

y_pred_dt_smotenn=model_dt_smotenn.predict(x_test)

In [142]:
print(classification_report(y_test,y_pred_dt_smotenn))

              precision    recall  f1-score   support

           0       0.89      0.70      0.78      1017
           1       0.49      0.77      0.60       390

    accuracy                           0.72      1407
   macro avg       0.69      0.73      0.69      1407
weighted avg       0.78      0.72      0.73      1407

In [143]:
model_rf_smotenn.fit(x_train_resampled,y_train_resampled)

y_pred_rf_smotenn=model_rf_smotenn.predict(x_test)

In [144]:
print(classification_report(y_test,y_pred_rf_smotenn))

              precision    recall  f1-score   support

           0       0.91      0.71      0.80      1017
           1       0.52      0.81      0.63       390

    accuracy                           0.74      1407
   macro avg       0.71      0.76      0.71      1407
weighted avg       0.80      0.74      0.75      1407

## XGBoost without SMOTEENN

In [145]:
model_xgb.fit(x_train,y_train)

y_pred_xgb=model_xgb.predict(x_test)

In [146]:
print(classification_report(y_test,y_pred_xgb))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1017
           1       0.63      0.52      0.57       390

    accuracy                           0.78      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.77      0.78      0.77      1407

## XGBoost with SMOTEENN

In [147]:
model_xgb_smotenn.fit(x_train_resampled,y_train_resampled)

y_pred_xgb_smotenn=model_xgb_smotenn.predict(x_test)

In [148]:
print(classification_report(y_test,y_pred_xgb_smotenn))

              precision    recall  f1-score   support

           0       0.90      0.73      0.80      1017
           1       0.52      0.79      0.63       390

    accuracy                           0.74      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.74      0.76      1407

## XGBoost with SMOTE

In [152]:
print("Before Counter ",Counter(y_train))

x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)

print("After Smote ",Counter(y_train_smote))

model_xgb_smote.fit(x_train_smote,y_train_smote)


y_pred_xgb_smote=model_xgb_smote.predict(x_test)

Before Counter  Counter({0: 4146, 1: 1479})
After Smote  Counter({0: 4146, 1: 4146})

In [153]:
print(classification_report(y_test,y_pred_xgb_smote))

              precision    recall  f1-score   support

           0       0.83      0.86      0.85      1017
           1       0.60      0.56      0.58       390

    accuracy                           0.78      1407
   macro avg       0.72      0.71      0.71      1407
weighted avg       0.77      0.78      0.77      1407

In [163]:
print("Before Adaysn : ",Counter(y_train))

x_train_adasyn,y_train_adasyn=adasyn.fit_resample(x_train,y_train)

print("After Adasyn : ",Counter(y_train_adasyn))

model_xgb_adasyn.fit(x_train_adasyn,y_train_adasyn)
y_pred_xgb_adasyn=model_xgb_adasyn.predict(x_test)


print("Accuracy :",accuracy_score(y_test,y_pred_xgb_adasyn))
print("Classification Report : \n",classification_report(y_test,y_pred_xgb_adasyn))
print("confusion Matrix: \n",confusion_matrix(y_test,y_pred_xgb_adasyn))

Before Adaysn :  Counter({0: 4146, 1: 1479})
After Adasyn :  Counter({0: 4146, 1: 4056})
Accuracy : 0.7739872068230277
Classification Report :
               precision    recall  f1-score   support

           0       0.83      0.86      0.85      1017
           1       0.60      0.55      0.58       390

    accuracy                           0.77      1407
   macro avg       0.72      0.71      0.71      1407
weighted avg       0.77      0.77      0.77      1407

confusion Matrix:
 [[873 144]
 [174 216]]

In [171]:
scale_pos_weight=(y_train==0).sum()/(y_train==1).sum()
print(f"Scale Pos Weight : {scale_pos_weight}")

model_xgb_weighted=XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'
)

model_xgb_weighted.fit(x_train,y_train)
y_pred_xgb_weighted=model_xgb_weighted.predict(x_test)


print("Accuracy Score is : ",accuracy_score(y_test,y_pred_xgb_weighted))
print("\n Classification Report is \n",classification_report(y_test,y_pred_xgb_weighted))
print("Confusion Matrix :\n",confusion_matrix(y_test,y_pred_xgb_weighted))

Scale Pos Weight : 2.8032454361054766
Accuracy Score is :  0.7583511016346838

 Classification Report is
               precision    recall  f1-score   support

           0       0.86      0.80      0.83      1017
           1       0.55      0.66      0.60       390

    accuracy                           0.76      1407
   macro avg       0.71      0.73      0.71      1407
weighted avg       0.77      0.76      0.76      1407

Confusion Matrix :
 [[810 207]
 [133 257]]

In [180]:
negative_count=(y_train==0).sum()
positive_count=(y_train==1).sum()
weighted_positive=negative_count/positive_count

print(f"Negative Class Count : {negative_count}")
print(f"Positive Class Count : {positive_count}")
print(f"Weighted For Positive Class : {weighted_positive}")


sample_weight=np.where(y_train==1,weighted_positive,1.0)

model_ada_weighted=AdaBoostClassifier(
    n_estimators=50,
    random_state=42
)

model_ada_weighted.fit(x_train,y_train,sample_weight=sample_weight)

y_pred_ada_weighted=model_ada_weighted.predict(x_test)

print("Adaboost with Sample Weighted Accuracy is : ",accuracy_score(y_test,y_pred_ada_weighted))
print("Classification Report is : \n",classification_report(y_test,y_pred_ada_weighted))
print("\n Confusion Matrix \n",confusion_matrix(y_test,y_pred_ada_weighted))

Negative Class Count : 4146
Positive Class Count : 1479
Weighted For Positive Class : 2.8032454361054766
Adaboost with Sample Weighted Accuracy is :  0.7533759772565742
Classification Report is :
               precision    recall  f1-score   support

           0       0.90      0.74      0.81      1017
           1       0.54      0.78      0.64       390

    accuracy                           0.75      1407
   macro avg       0.72      0.76      0.72      1407
weighted avg       0.80      0.75      0.76      1407


 Confusion Matrix
 [[756 261]
 [ 86 304]]

## **Hyper Parameter Optimization**

In [184]:
param_grid={
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight] 

}
xgb=XGBClassifier(random_state=42,eval_metric='logloss')

search=RandomizedSearchCV(
    xgb,
    param_grid,
    n_iter=50,
    cv=5,
    scoring='f1',
    random_state=42,
    n_jobs=-1

)


search.fit(x_train,y_train)
print("Best Parameters : ",search.best_params_)
print("Best Cv F1 Score ",search.best_score_)

best_model=search.best_estimator_
y_pred_best=best_model.predict(x_test)
print("\n Classification Report is \n",classification_report(y_test,y_pred_best))

Best Parameters :  {'subsample': 0.8, 'scale_pos_weight': np.float64(2.8032454361054766), 'n_estimators': 200, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.05, 'gamma': 0.2, 'colsample_bytree': 0.8}
Best Cv F1 Score  0.6293339972808902

 Classification Report is
               precision    recall  f1-score   support

           0       0.90      0.74      0.81      1017
           1       0.54      0.78      0.64       390

    accuracy                           0.75      1407
   macro avg       0.72      0.76      0.73      1407
weighted avg       0.80      0.75      0.76      1407

In [187]:
joblib.dump(best_model,'../models/best_xgboost_churn_model.pkl')
print("Best model Successfully saved as 'best_xgboost_churn_model.pkl' ")

Best model Successfully saved as 'best_xgboost_churn_model.pkl'

## Trying out few more techniques

In [193]:
model_rf.fit(x_train,y_train)
y_pred_rf=model_rf.predict(x_test)

print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.89      0.72      0.80      1017
           1       0.51      0.77      0.62       390

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.71      1407
weighted avg       0.79      0.73      0.75      1407

In [194]:
model_cat.fit(x_train,y_train)
y_pred_cat=model_cat.predict(x_test)
print(classification_report(y_test,y_pred_cat))

              precision    recall  f1-score   support

           0       0.88      0.76      0.82      1017
           1       0.54      0.73      0.62       390

    accuracy                           0.75      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.75      0.76      1407

In [200]:
model_lgb=LGBMClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42
)
model_lgb.fit(x_train,y_train)
y_pred_lgb=model_lgb.predict(x_test)
print(classification_report(y_test,y_pred_lgb))

              precision    recall  f1-score   support

           0       0.88      0.77      0.82      1017
           1       0.54      0.72      0.62       390

    accuracy                           0.75      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.78      0.75      0.76      1407

## **Optuna fine tuning**

In [203]:
def objective(trial):
    params={
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  # L1 regularization
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), # L2 regularization
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'

    }
    model=XGBClassifier(**params)

    f1_scorer=make_scorer(f1_score,average='binary',pos_label=1)
    score=cross_val_score(model,x_train,y_train,cv=5,scoring=f1_scorer,n_jobs=-1).mean()
    return score

study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)
print("Best Parameters ",study.best_params)
print("Best CV F1 Score : ",study.best_value)

best_model_optuna=XGBClassifier(**study.best_params)
best_model_optuna.fit(x_train,y_train)
y_pred_optuna=best_model_optuna.predict(x_test)
print(classification_report(y_test,y_pred_optuna))

[I 2026-04-02 00:32:35,122] A new study created in memory with name: no-name-ac333e5c-280f-4725-8049-d84a69da6865
[I 2026-04-02 00:32:37,831] Trial 0 finished with value: 0.629252729482298 and parameters: {'max_depth': 7, 'learning_rate': 0.011779501811490874, 'n_estimators': 256, 'subsample': 0.8424717203688067, 'colsample_bytree': 0.8846222229067306, 'min_child_weight': 1, 'gamma': 0.3035622121240465, 'reg_alpha': 0.708132289641513, 'reg_lambda': 1.8477871460748658, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:39,991] Trial 1 finished with value: 0.5816361113518731 and parameters: {'max_depth': 5, 'learning_rate': 0.028074273844526123, 'n_estimators': 330, 'subsample': 0.8690493057221444, 'colsample_bytree': 0.7670059225747811, 'min_child_weight': 6, 'gamma': 0.4290770047483449, 'reg_alpha': 0.7372080287957464, 'reg_lambda': 1.977525444348415, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:42,239] Trial 2 finished with value: 0.6099194343286793 and parameters: {'max_depth': 3, 'learning_rate': 0.20254072318786365, 'n_estimators': 552, 'subsample': 0.9253881094534586, 'colsample_bytree': 0.8395343415186749, 'min_child_weight': 4, 'gamma': 0.006526876311005736, 'reg_alpha': 0.6392302001051389, 'reg_lambda': 0.8015260607594725, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:44,552] Trial 3 finished with value: 0.5658104840043079 and parameters: {'max_depth': 9, 'learning_rate': 0.24281979493211314, 'n_estimators': 874, 'subsample': 0.6482437508010164, 'colsample_bytree': 0.6345316848571506, 'min_child_weight': 8, 'gamma': 0.3633222636549978, 'reg_alpha': 0.9229812927834325, 'reg_lambda': 1.7106289891757775, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:45,341] Trial 4 finished with value: 0.5600568526711521 and parameters: {'max_depth': 6, 'learning_rate': 0.06283369722098589, 'n_estimators': 738, 'subsample': 0.7691024696425827, 'colsample_bytree': 0.6631797055586791, 'min_child_weight': 10, 'gamma': 0.10326312631907403, 'reg_alpha': 0.36275136793877927, 'reg_lambda': 1.969402247954519, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:45,679] Trial 5 finished with value: 0.5840140554021871 and parameters: {'max_depth': 4, 'learning_rate': 0.044327418306709415, 'n_estimators': 270, 'subsample': 0.9370433320773055, 'colsample_bytree': 0.8210633126881213, 'min_child_weight': 7, 'gamma': 0.04864534421437827, 'reg_alpha': 0.38709929713830526, 'reg_lambda': 0.3944411450386962, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:46,526] Trial 6 finished with value: 0.5609052193642803 and parameters: {'max_depth': 9, 'learning_rate': 0.034376719129332704, 'n_estimators': 541, 'subsample': 0.8918956296849774, 'colsample_bytree': 0.7579455576324514, 'min_child_weight': 2, 'gamma': 0.23680064967452052, 'reg_alpha': 0.9507966017234095, 'reg_lambda': 1.7523937280133086, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:47,197] Trial 7 finished with value: 0.5677301233800398 and parameters: {'max_depth': 3, 'learning_rate': 0.058407681623050635, 'n_estimators': 894, 'subsample': 0.9959134332104651, 'colsample_bytree': 0.8763972018611037, 'min_child_weight': 3, 'gamma': 0.05208566739979492, 'reg_alpha': 0.251492777737902, 'reg_lambda': 1.1833245377695158, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:48,380] Trial 8 finished with value: 0.6171272942136314 and parameters: {'max_depth': 7, 'learning_rate': 0.011650952635091265, 'n_estimators': 922, 'subsample': 0.797192356330443, 'colsample_bytree': 0.9702304002483357, 'min_child_weight': 10, 'gamma': 0.4554395390175062, 'reg_alpha': 0.05793718589788743, 'reg_lambda': 1.6705778256446704, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:48,756] Trial 9 finished with value: 0.5854207937822438 and parameters: {'max_depth': 3, 'learning_rate': 0.02901173280182599, 'n_estimators': 379, 'subsample': 0.9155061107244633, 'colsample_bytree': 0.727045827329044, 'min_child_weight': 9, 'gamma': 0.3987492515212942, 'reg_alpha': 0.7156490045078495, 'reg_lambda': 0.7430221206197971, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:49,100] Trial 10 finished with value: 0.6258637653956972 and parameters: {'max_depth': 7, 'learning_rate': 0.011563233075266164, 'n_estimators': 129, 'subsample': 0.7142506129600952, 'colsample_bytree': 0.9968814191369705, 'min_child_weight': 1, 'gamma': 0.26434225072582823, 'reg_alpha': 0.5582952633545878, 'reg_lambda': 1.3323172992582464, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 0 with value: 0.629252729482298.
[I 2026-04-02 00:32:49,443] Trial 11 finished with value: 0.6295077875744538 and parameters: {'max_depth': 7, 'learning_rate': 0.012649556061443225, 'n_estimators': 117, 'subsample': 0.6949519264871731, 'colsample_bytree': 0.9897348735356507, 'min_child_weight': 1, 'gamma': 0.26546096844789824, 'reg_alpha': 0.5704520787337288, 'reg_lambda': 1.3050000814287095, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:49,791] Trial 12 finished with value: 0.6279068069298288 and parameters: {'max_depth': 8, 'learning_rate': 0.016509518967777984, 'n_estimators': 105, 'subsample': 0.6309610779867639, 'colsample_bytree': 0.9142285251900658, 'min_child_weight': 1, 'gamma': 0.26110005560693894, 'reg_alpha': 0.7669790551085431, 'reg_lambda': 1.356989783623666, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:50,355] Trial 13 finished with value: 0.6237332303995842 and parameters: {'max_depth': 10, 'learning_rate': 0.019057862291443736, 'n_estimators': 222, 'subsample': 0.7189040273940597, 'colsample_bytree': 0.9297923242611459, 'min_child_weight': 4, 'gamma': 0.18976313056881144, 'reg_alpha': 0.5075074228172523, 'reg_lambda': 0.0689361085896727, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:50,974] Trial 14 finished with value: 0.5940624329834907 and parameters: {'max_depth': 6, 'learning_rate': 0.09831968590207045, 'n_estimators': 473, 'subsample': 0.836850093454001, 'colsample_bytree': 0.9289844413182949, 'min_child_weight': 3, 'gamma': 0.3514430916128163, 'reg_alpha': 0.8405465600554024, 'reg_lambda': 1.4776568982368137, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:51,617] Trial 15 finished with value: 0.6275115888168163 and parameters: {'max_depth': 8, 'learning_rate': 0.0179942997350982, 'n_estimators': 206, 'subsample': 0.7117876853730205, 'colsample_bytree': 0.8767175092895838, 'min_child_weight': 1, 'gamma': 0.32038914394050466, 'reg_alpha': 0.6322195491210382, 'reg_lambda': 1.035877666057552, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:52,193] Trial 16 finished with value: 0.6254444556815721 and parameters: {'max_depth': 5, 'learning_rate': 0.010345156355682712, 'n_estimators': 410, 'subsample': 0.764828363842721, 'colsample_bytree': 0.9996460580926583, 'min_child_weight': 5, 'gamma': 0.16474965722205254, 'reg_alpha': 0.3983645671926461, 'reg_lambda': 1.5705930080890207, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:53,115] Trial 17 finished with value: 0.5659615653190667 and parameters: {'max_depth': 8, 'learning_rate': 0.10098400073859701, 'n_estimators': 637, 'subsample': 0.6729313922336922, 'colsample_bytree': 0.8651096828287728, 'min_child_weight': 2, 'gamma': 0.2999689999527175, 'reg_alpha': 0.23960394647627126, 'reg_lambda': 0.6887572503390251, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:53,585] Trial 18 finished with value: 0.6263789310186365 and parameters: {'max_depth': 5, 'learning_rate': 0.021883525869071902, 'n_estimators': 289, 'subsample': 0.607629236301058, 'colsample_bytree': 0.9456129960559153, 'min_child_weight': 3, 'gamma': 0.18798872011655943, 'reg_alpha': 0.594383371717973, 'reg_lambda': 1.1307596604145929, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:54,044] Trial 19 finished with value: 0.6291487087557324 and parameters: {'max_depth': 7, 'learning_rate': 0.014197194088407378, 'n_estimators': 173, 'subsample': 0.8403323692450734, 'colsample_bytree': 0.8944932902293521, 'min_child_weight': 2, 'gamma': 0.1406504577995072, 'reg_alpha': 0.44834566750654464, 'reg_lambda': 1.8358200825235087, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:54,987] Trial 20 finished with value: 0.6211892653642219 and parameters: {'max_depth': 6, 'learning_rate': 0.022847434307128402, 'n_estimators': 746, 'subsample': 0.761147097428823, 'colsample_bytree': 0.9605817797205629, 'min_child_weight': 5, 'gamma': 0.23371804732395177, 'reg_alpha': 0.8694094871741597, 'reg_lambda': 1.3969705406665893, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:55,364] Trial 21 finished with value: 0.6283029475320097 and parameters: {'max_depth': 7, 'learning_rate': 0.014862272741856674, 'n_estimators': 172, 'subsample': 0.8417117035203662, 'colsample_bytree': 0.8992658120501631, 'min_child_weight': 2, 'gamma': 0.13551466412892219, 'reg_alpha': 0.5037238037996866, 'reg_lambda': 1.7865188198973336, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:55,659] Trial 22 finished with value: 0.6284829350726084 and parameters: {'max_depth': 7, 'learning_rate': 0.013950262394903577, 'n_estimators': 100, 'subsample': 0.8204080908287371, 'colsample_bytree': 0.8091741308121138, 'min_child_weight': 1, 'gamma': 0.30339506325388266, 'reg_alpha': 0.4429626994739898, 'reg_lambda': 1.8958595608735398, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:56,151] Trial 23 finished with value: 0.6286376127592878 and parameters: {'max_depth': 8, 'learning_rate': 0.01025879647600421, 'n_estimators': 216, 'subsample': 0.8692159901609633, 'colsample_bytree': 0.8484419311793502, 'min_child_weight': 2, 'gamma': 0.49059490390413074, 'reg_alpha': 0.24814141285674562, 'reg_lambda': 1.5179492674805513, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:56,862] Trial 24 finished with value: 0.6234670612844007 and parameters: {'max_depth': 9, 'learning_rate': 0.014718421609604236, 'n_estimators': 346, 'subsample': 0.8086681379455891, 'colsample_bytree': 0.8894009353248616, 'min_child_weight': 4, 'gamma': 0.1104009491410137, 'reg_alpha': 0.7091119002720154, 'reg_lambda': 1.8342275979963452, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:57,290] Trial 25 finished with value: 0.6245809509504519 and parameters: {'max_depth': 6, 'learning_rate': 0.03493562862662953, 'n_estimators': 274, 'subsample': 0.7867626133019451, 'colsample_bytree': 0.9693218124946513, 'min_child_weight': 1, 'gamma': 0.22606140611633013, 'reg_alpha': 0.31344635963271406, 'reg_lambda': 1.2523555471118777, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:57,926] Trial 26 finished with value: 0.6200124910707248 and parameters: {'max_depth': 7, 'learning_rate': 0.023944265131718278, 'n_estimators': 432, 'subsample': 0.7374149044817858, 'colsample_bytree': 0.7792587416127742, 'min_child_weight': 3, 'gamma': 0.3529480058400397, 'reg_alpha': 0.15195939235524453, 'reg_lambda': 1.607580634057959, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:58,410] Trial 27 finished with value: 0.6276923236674345 and parameters: {'max_depth': 8, 'learning_rate': 0.012675731665582753, 'n_estimators': 165, 'subsample': 0.9711344074553895, 'colsample_bytree': 0.9247006500755939, 'min_child_weight': 2, 'gamma': 0.20529754892591628, 'reg_alpha': 0.8144918449385701, 'reg_lambda': 0.9159978869464371, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:59,082] Trial 28 finished with value: 0.5950488543586031 and parameters: {'max_depth': 10, 'learning_rate': 0.07892869739366237, 'n_estimators': 269, 'subsample': 0.8574508372334144, 'colsample_bytree': 0.6949344690113857, 'min_child_weight': 1, 'gamma': 0.27433285723332657, 'reg_alpha': 0.47057361636737916, 'reg_lambda': 0.5717536197954436, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:59,543] Trial 29 finished with value: 0.5830360717023886 and parameters: {'max_depth': 5, 'learning_rate': 0.029214765837558263, 'n_estimators': 333, 'subsample': 0.8836979475131346, 'colsample_bytree': 0.8449570141719939, 'min_child_weight': 6, 'gamma': 0.3907796429673086, 'reg_alpha': 0.6683286079057761, 'reg_lambda': 1.9819811553428983, 'scale_pos_weight': 1}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:32:59,913] Trial 30 finished with value: 0.6005534699794847 and parameters: {'max_depth': 6, 'learning_rate': 0.16597797673251632, 'n_estimators': 172, 'subsample': 0.6757773432573242, 'colsample_bytree': 0.780780553639107, 'min_child_weight': 2, 'gamma': 0.15103969618265423, 'reg_alpha': 0.5590719812490128, 'reg_lambda': 1.8518435957379982, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 11 with value: 0.6295077875744538.
[I 2026-04-02 00:33:00,417] Trial 31 finished with value: 0.6300431726256368 and parameters: {'max_depth': 8, 'learning_rate': 0.010863190374938452, 'n_estimators': 212, 'subsample': 0.8553699790072258, 'colsample_bytree': 0.8489706581072227, 'min_child_weight': 2, 'gamma': 0.49976900704396576, 'reg_alpha': 0.11372722104277638, 'reg_lambda': 1.4999735874408935, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:00,847] Trial 32 finished with value: 0.6296230131634356 and parameters: {'max_depth': 7, 'learning_rate': 0.017331412773579025, 'n_estimators': 227, 'subsample': 0.8323879651751058, 'colsample_bytree': 0.8156196373792236, 'min_child_weight': 3, 'gamma': 0.49307474932591405, 'reg_alpha': 0.11532515652109702, 'reg_lambda': 1.5134215729964196, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:01,426] Trial 33 finished with value: 0.6256348647324215 and parameters: {'max_depth': 9, 'learning_rate': 0.019345485074795863, 'n_estimators': 238, 'subsample': 0.8979503433452332, 'colsample_bytree': 0.8244618709004885, 'min_child_weight': 3, 'gamma': 0.49393403394806085, 'reg_alpha': 0.07734845330461154, 'reg_lambda': 1.4534934281090512, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:03,089] Trial 34 finished with value: 0.6141864713839345 and parameters: {'max_depth': 8, 'learning_rate': 0.01233966799661111, 'n_estimators': 982, 'subsample': 0.8198765758767487, 'colsample_bytree': 0.7411029690027895, 'min_child_weight': 4, 'gamma': 0.4487350955897712, 'reg_alpha': 0.11606179001650807, 'reg_lambda': 1.6394740851635476, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:03,766] Trial 35 finished with value: 0.6296039240357449 and parameters: {'max_depth': 7, 'learning_rate': 0.010397232213245733, 'n_estimators': 320, 'subsample': 0.9417915483470819, 'colsample_bytree': 0.7927457972552125, 'min_child_weight': 1, 'gamma': 0.4141872007252946, 'reg_alpha': 0.18059869468950618, 'reg_lambda': 1.2625517969631948, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:04,497] Trial 36 finished with value: 0.6227048555803962 and parameters: {'max_depth': 8, 'learning_rate': 0.016866037232985322, 'n_estimators': 305, 'subsample': 0.9335309453900299, 'colsample_bytree': 0.7933062382260803, 'min_child_weight': 1, 'gamma': 0.42430332318331776, 'reg_alpha': 0.17215829780703595, 'reg_lambda': 0.9892783685928153, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:05,374] Trial 37 finished with value: 0.5770541240725328 and parameters: {'max_depth': 9, 'learning_rate': 0.010191838122917192, 'n_estimators': 477, 'subsample': 0.9551061629068504, 'colsample_bytree': 0.6093973500185457, 'min_child_weight': 3, 'gamma': 0.46710939477389357, 'reg_alpha': 0.023036552033810026, 'reg_lambda': 1.2771590432255309, 'scale_pos_weight': 1}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:05,935] Trial 38 finished with value: 0.6276690782499015 and parameters: {'max_depth': 6, 'learning_rate': 0.012883860284758346, 'n_estimators': 348, 'subsample': 0.9733813891751065, 'colsample_bytree': 0.7112249423020361, 'min_child_weight': 4, 'gamma': 0.4217270489010465, 'reg_alpha': 0.1997792986446411, 'reg_lambda': 1.0911242550909248, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:06,314] Trial 39 finished with value: 0.581589426690253 and parameters: {'max_depth': 7, 'learning_rate': 0.039650254435242144, 'n_estimators': 151, 'subsample': 0.9116390444204799, 'colsample_bytree': 0.7623270400310385, 'min_child_weight': 2, 'gamma': 0.4732979482854587, 'reg_alpha': 0.3451787449130286, 'reg_lambda': 1.2311672881917952, 'scale_pos_weight': 1}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:06,706] Trial 40 finished with value: 0.6179675501763924 and parameters: {'max_depth': 7, 'learning_rate': 0.0502471213944432, 'n_estimators': 237, 'subsample': 0.7877961875867693, 'colsample_bytree': 0.6869542114764354, 'min_child_weight': 7, 'gamma': 0.3929429681241252, 'reg_alpha': 0.30111906135785066, 'reg_lambda': 0.8538652576465457, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:07,413] Trial 41 finished with value: 0.6279633107813452 and parameters: {'max_depth': 7, 'learning_rate': 0.010063934873338162, 'n_estimators': 386, 'subsample': 0.8584910534401654, 'colsample_bytree': 0.8265982359731857, 'min_child_weight': 1, 'gamma': 0.4398927398120449, 'reg_alpha': 0.0064752190294977835, 'reg_lambda': 1.684889599991503, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.
[I 2026-04-02 00:33:08,739] Trial 42 finished with value: 0.6191044372179608 and parameters: {'max_depth': 8, 'learning_rate': 0.01594554155401256, 'n_estimators': 618, 'subsample': 0.8705924095912214, 'colsample_bytree': 0.8023912722885347, 'min_child_weight': 1, 'gamma': 0.41442661379607876, 'reg_alpha': 0.7664504248999908, 'reg_lambda': 1.3637958045093708, 'scale_pos_weight': np.float64(2.8032454361054766)}. Best is trial 31 with value: 0.6300431726256368.

Best Parameters  {'max_depth': 7, 'learning_rate': 0.016185643993294006, 'n_estimators': 192, 'subsample': 0.873483782608229, 'colsample_bytree': 0.8126365338356265, 'min_child_weight': 2, 'gamma': 0.48632100527915945, 'reg_alpha': 0.26988138342930335, 'reg_lambda': 1.698154300691567, 'scale_pos_weight': np.float64(2.8032454361054766)}
Best CV F1 Score :  0.6304188049947953
              precision    recall  f1-score   support

           0       0.89      0.75      0.81      1017
           1       0.54      0.76      0.63       390

    accuracy                           0.75      1407
   macro avg       0.72      0.76      0.72      1407
weighted avg       0.79      0.75      0.76      1407

In [204]:
joblib.dump(best_model_optuna,'../models/best_optuna_churn_model.pkl')
print("Best Model Succesfully saved as 'best_optuna_churn_model.pkl' ")

Best Model Succesfully saved as 'best_optuna_churn_model.pkl'

In [205]:
joblib.dump(model_ada_weighted,'../models/ada_boost_churn_model.pkl')
print("best model  succesfully saved as 'ada_boost_churn_model.pkl'")

best model  succesfully saved as 'ada_boost_churn_model.pkl'