In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,make_scorer,f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.model_selection import train_test_split,RandomizedSearchCV,cross_val_score
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE,ADASYN
from xgboost import  XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from collections import Counter
import warnings
import joblib
import optuna

In [107]:
warnings.filterwarnings('ignore')
model_dt=DecisionTreeClassifier()
model_dt1=DecisionTreeClassifier()
model_dt2=DecisionTreeClassifier()
model_dt_smeen=DecisionTreeClassifier()
model_rf_smenn=RandomForestClassifier(n_estimators=500)
model_rf1=RandomForestClassifier(class_weight='balanced',n_estimators=300,max_depth=6,random_state=42)
model_xbg=XGBClassifier(random_state=42)
model_xgb_smote=XGBClassifier(random_state=42)
model_xgb_smenn=XGBClassifier(random_state=42)
model_xgb_adasyn=XGBClassifier(random_state=42)
model_xgb_randomizeds=XGBClassifier(random_state=42,eval_metric='logloss')
model_lgb=LGBMClassifier(random_state=42)
model_catb=CatBoostClassifier(auto_class_weights='Balanced',verbose=0,random_state=42)
model_ada_weighted=AdaBoostClassifier(random_state=42,n_estimators=50)
sc=StandardScaler()
mms=MinMaxScaler()
smenn=SMOTEENN()
smote=SMOTE(random_state=42)
adasyn=ADASYN(random_state=42)

In [108]:
df=pd.read_csv('../data/Customer-Churn.csv')

In [109]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [110]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

## **Churn Rate**: 26.53%

- Which means, 26.53% of the customers churn out of this telecom company

In [111]:
y=df['Churn']

x=df.drop(columns=['customerID','Churn'])


print("Shape of x is : ",x.shape)
print("Shape of y is : ",y.shape)

Shape of x is :  (7043, 19)
Shape of y is :  (7043,)

## Train Test Split

In [112]:
x=pd.get_dummies(x,drop_first=True)
y=df['Churn'].map({'No':0,'Yes':1})

In [113]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Model Building

In [114]:
model_dt=DecisionTreeClassifier()
model_dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [115]:
y_pred_dt=model_dt.predict(x_test)

In [116]:
print("Classification Report : ")
print(classification_report(y_test,y_pred_dt))

Classification Report :
              precision    recall  f1-score   support

           0       0.81      0.87      0.84      1009
           1       0.59      0.49      0.53       400

    accuracy                           0.76      1409
   macro avg       0.70      0.68      0.69      1409
weighted avg       0.75      0.76      0.75      1409

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## Initial Insights

- Base model has a accuracy of 76% which is not reliable because of the imbalanced dataset
- TotalCharges needs to be a float/int type (Data Cleaning)
- Need to perform Feature Scaling

## Data Cleaning

In [118]:
telco_df=df.copy()

In [119]:
telco_df.TotalCharges=pd.to_numeric(telco_df.TotalCharges,errors='coerce')

In [120]:
telco_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [121]:
telco_df.loc[telco_df['TotalCharges'].isnull()==True]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [122]:
telco_df.dropna(how='any',inplace=True)

In [123]:
telco_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [124]:
telco_df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [125]:
labels=['1-12','13-24','25-36','37-48','49-60',
        61-72]
bins=[0,12,24,36,48,60,72]
telco_df['tenure_group']=pd.cut(x=telco_df.tenure,labels=labels,bins=bins,right=True,include_lowest=True)

print(telco_df[['tenure','tenure_group']].head(10))

print(telco_df['tenure_group'].value_counts().sort_index())

   tenure tenure_group
0       1         1-12
1      34        25-36
2       2         1-12
3      45        37-48
4       2         1-12
5       8         1-12
6      22        13-24
7      10         1-12
8      28        25-36
9      62          -11
tenure_group
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
-11      1407
Name: count, dtype: int64

In [126]:
telco_df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [127]:
y=telco_df['Churn']
x=telco_df.drop(columns=['Churn','customerID','tenure'])

print("shape of x is : ",x.shape)
print("shape of y is :",y.shape)

shape of x is :  (7032, 19)
shape of y is : (7032,)

In [128]:
x

,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,tenure_group
0,Female,0,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1-12
1,Male,0,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,25-36
2,Male,0,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1-12
3,Male,0,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,37-48
4,Female,0,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,13-24
7039,Female,0,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,-11
7040,Female,0,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,1-12
7041,Male,1,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,1-12
7042,Male,0,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,-11

In [129]:
x=pd.get_dummies(x,drop_first=True)
y=telco_df['Churn'].map({'No':0,'Yes':1})

In [130]:
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_13-24,tenure_group_25-36,tenure_group_37-48,tenure_group_49-60,tenure_group_-11
0,0,29.85,29.85,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
1,0,56.95,1889.50,True,False,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,0,53.85,108.15,True,False,False,True,False,False,False,...,False,True,False,False,True,False,False,False,False,False
3,0,42.30,1840.75,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,False,False,False,True,False,False,True,...,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,84.80,1990.50,True,True,True,True,False,True,False,...,False,True,False,False,True,True,False,False,False,False
7039,0,103.20,7362.90,False,True,True,True,False,True,True,...,False,True,True,False,False,False,False,False,False,True
7040,0,29.60,346.45,False,True,True,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
7041,1,74.40,306.60,True,True,False,True,False,True,True,...,False,True,False,False,True,False,False,False,False,False
7042,0,105.65,6844.50,True,False,False,True,False,False,True,...,True,True,False,False,False,False,False,False,False,True

In [131]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Feature Scaling

In [132]:
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

In [133]:
model_dt1.fit(x_train_sc,y_train)
y_pred_dt1=model_dt1.predict(x_test_sc)
print("Classification Report : \n",classification_report(y_test,y_pred_dt1))

Classification Report :
               precision    recall  f1-score   support

           0       0.81      0.82      0.81      1033
           1       0.48      0.47      0.47       374

    accuracy                           0.72      1407
   macro avg       0.65      0.64      0.64      1407
weighted avg       0.72      0.72      0.72      1407

## Feature Scaling - MinMaxScaler

In [134]:
x_train_mms=mms.fit_transform(x_train)
x_test_mms=mms.transform(x_test)

In [135]:
model_dt2.fit(x_train_mms,y_train)
y_pred_dt2=model_dt2.predict(x_test)
print("Classification Report is : \n",classification_report(y_test,y_pred_dt2))

Classification Report is :
               precision    recall  f1-score   support

           0       0.74      0.88      0.80      1033
           1       0.28      0.13      0.18       374

    accuracy                           0.68      1407
   macro avg       0.51      0.50      0.49      1407
weighted avg       0.61      0.68      0.63      1407

## SMOTEENN () [UpSampling + ENN)

In [136]:
x_train_resampled,y_train_resampled=smenn.fit_resample(x_train,y_train)

In [137]:
model_dt_smeen.fit(x_train_resampled,y_train_resampled)
y_pred_dt2_smeen=model_dt_smeen.predict(x_test)

print("Classification Report is :",classification_report(y_test,y_pred_dt2_smeen))

Classification Report is :               precision    recall  f1-score   support

           0       0.86      0.73      0.79      1033
           1       0.48      0.67      0.56       374

    accuracy                           0.72      1407
   macro avg       0.67      0.70      0.68      1407
weighted avg       0.76      0.72      0.73      1407

### Random Forest with Smotenn

In [138]:
model_rf_smenn.fit(x_train_resampled,y_train_resampled)
y_pred_rf_smenn=model_rf_smenn.predict(x_test)

In [139]:
print("Classification Report : \n",classification_report(y_test,y_pred_rf_smenn))

Classification Report :
               precision    recall  f1-score   support

           0       0.88      0.77      0.82      1033
           1       0.53      0.72      0.61       374

    accuracy                           0.76      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.79      0.76      0.77      1407

### Xgbbost without SMOTEENN

In [140]:
model_xbg.fit(x_train,y_train)
Y_pred_xgb=model_xbg.predict(x_test)

print("Classification Report is : \n",classification_report(y_test,Y_pred_xgb))

Classification Report is :
               precision    recall  f1-score   support

           0       0.83      0.88      0.86      1033
           1       0.61      0.51      0.55       374

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.78      1407

### Xgbbost with SMOTEENN

In [141]:
model_xgb_smenn.fit(x_train_resampled,y_train_resampled)
y_pred_xgb_smenn=model_xgb_smenn.predict(x_test)
print("Classification Report is :\n",classification_report(y_test,y_pred_xgb_smenn))

Classification Report is :
               precision    recall  f1-score   support

           0       0.88      0.78      0.82      1033
           1       0.53      0.70      0.60       374

    accuracy                           0.76      1407
   macro avg       0.70      0.74      0.71      1407
weighted avg       0.78      0.76      0.76      1407

### XGBoost with SMOTE

In [142]:
print("Before Smote :",Counter(y_train))

x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)

print("After Smote : ",Counter(y_train_smote))

model_xgb_smote.fit(x_train_smote,y_train_smote)

y_pred_xgb_smote=model_xgb_smote.predict(x_test)

print("classification report is : ",classification_report(y_test,y_pred_xgb_smote))

Before Smote : Counter({0: 4130, 1: 1495})
After Smote :  Counter({1: 4130, 0: 4130})
classification report is :                precision    recall  f1-score   support

           0       0.84      0.84      0.84      1033
           1       0.55      0.54      0.55       374

    accuracy                           0.76      1407
   macro avg       0.69      0.69      0.69      1407
weighted avg       0.76      0.76      0.76      1407

### Xgboost with Adaysn

In [143]:
print("Before Adaysn : ",Counter(y_train))

x_train_adaysn,y_train_adaysn=adasyn.fit_resample(x_train,y_train)

print("After Adasyn : ",Counter(y_train_adaysn))

model_xgb_adasyn.fit(x_train_adaysn,y_train_adaysn)

y_pred_xgb_adasyn=model_xgb_adasyn.predict(x_test)

print("Accuracy is : ",accuracy_score(y_test,y_pred_xgb_adasyn))
print("Classification Report is : ",classification_report(y_test,y_pred_xgb_adasyn))
print("confusion matrix is : \n",confusion_matrix(y_test,y_pred_xgb_adasyn))

Before Adaysn :  Counter({0: 4130, 1: 1495})
After Adasyn :  Counter({1: 4187, 0: 4130})
Accuracy is :  0.7661691542288557
Classification Report is :                precision    recall  f1-score   support

           0       0.84      0.85      0.84      1033
           1       0.56      0.55      0.55       374

    accuracy                           0.77      1407
   macro avg       0.70      0.70      0.70      1407
weighted avg       0.76      0.77      0.77      1407

confusion matrix is :
 [[874 159]
 [170 204]]

In [144]:
scale_pos_weight=(y_train==0).sum()/(y_train==1).sum()
print("Scale pos Weight is : ",scale_pos_weight)

model_xgb_weighted=XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    eval_metric='logloss'
)

model_xgb_weighted.fit(x_train,y_train)
y_pred_xgb_weighted=model_xgb_weighted.predict(x_test)

print("Accuracy score is : ",accuracy_score(y_test,y_pred_xgb_weighted))
print("classification_report is :\n ",classification_report(y_test,y_pred_xgb_weighted))
print("confusion_matrix is :\n",confusion_matrix(y_test,y_pred_xgb_weighted))

Scale pos Weight is :  2.762541806020067
Accuracy score is :  0.7668798862828714
classification_report is :
                precision    recall  f1-score   support

           0       0.87      0.80      0.83      1033
           1       0.55      0.68      0.61       374

    accuracy                           0.77      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.79      0.77      0.77      1407

confusion_matrix is :
 [[823 210]
 [118 256]]

### Adaboost with Weighted sample Weight

In [145]:
negative_count=(y_train==0).sum()
positive_count=(y_train==1).sum()
weighted_positive=negative_count/positive_count
print("Negative Weight is : ",negative_count)
print("Postive Count is : ",positive_count)
print("weighted is :",weighted_positive)

sample_weight=np.where(y_train==1,weighted_positive,1.0)

model_ada_weighted.fit(x_train,y_train,sample_weight=sample_weight)

y_pred_ada_weighted=model_ada_weighted.predict(x_test)

print("\nAdaboost with Sample Weighting accuracy is :\n",accuracy_score(y_test,y_pred_ada_weighted))
print("\n Classification Report \n",classification_report(y_test,y_pred_ada_weighted))
print("\nConfusion Matrix is : \n",confusion_matrix(y_test,y_pred_ada_weighted))

Negative Weight is :  4130
Postive Count is :  1495
weighted is : 2.762541806020067

Adaboost with Sample Weighting accuracy is :
 0.7455579246624022

 Classification Report
               precision    recall  f1-score   support

           0       0.90      0.74      0.81      1033
           1       0.51      0.77      0.62       374

    accuracy                           0.75      1407
   macro avg       0.71      0.75      0.71      1407
weighted avg       0.80      0.75      0.76      1407


Confusion Matrix is :
 [[761 272]
 [ 86 288]]

## **Hyper Parameter Optimization**

In [146]:
param_grid={
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight]
}
xgb=XGBClassifier(
    random_state=42,eval_metric='logloss'
)

search=RandomizedSearchCV(
                            xgb,
                            param_grid,
                            n_iter=50,
                            cv=5,
                            n_jobs=-1,
                            scoring='f1',
                            random_state=42
                              )
search.fit(x_train,y_train)

print("best Parameters :\n",search.best_params_)
print("Best CV F11 score is :",search.best_score_)

best_model=search.best_estimator_
y_pred_randomized=best_model.predict(x_test)
print("\n Test Classification Report is : \n",classification_report(y_test,y_pred_randomized))

best Parameters :
 {'subsample': 0.8, 'scale_pos_weight': np.float64(2.762541806020067), 'n_estimators': 400, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.01, 'gamma': 0, 'colsample_bytree': 0.7}
Best CV F11 score is : 0.6340280623972054

 Test Classification Report is :
               precision    recall  f1-score   support

           0       0.91      0.72      0.81      1033
           1       0.51      0.80      0.63       374

    accuracy                           0.74      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.74      0.76      1407

In [147]:
joblib.dump(search,"../models/best_xgboost_churn_model.pkl")
print("Best model saved succesfully saved as best_xgboost_churn_model.pkl")

Best model saved succesfully saved as best_xgboost_churn_model.pkl

### Trying out few more techniques

In [148]:
model_rf1.fit(x_train,y_train)
y_pred_rf1=model_rf1.predict(x_test)
print("Classification Report is :\n",classification_report(y_test,y_pred_rf1))

Classification Report is :
               precision    recall  f1-score   support

           0       0.90      0.70      0.79      1033
           1       0.49      0.79      0.60       374

    accuracy                           0.72      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.72      0.74      1407

### LightGBM Model

In [149]:
model_lgb.fit(x_train,y_train)
y_pred_lgb=model_lgb.predict(x_test)
print("classification report is : \n",classification_report(y_test,y_pred_lgb))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1495, number of negative: 4130
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000166 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 574
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.265778 -> initscore=-1.016151
[LightGBM] [Info] Start training from score -1.016151
classification report is :
               precision    recall  f1-score   support

           0       0.82      0.89      0.86      1033
           1       0.61      0.48      0.54       374

    accuracy                           0.78      1407
   macro avg       0.72      0.68      0.70      1407
weighted avg       0.77      0.78      0.77      1407

### caatboost Model

In [150]:
model_catb.fit(x_train,y_train)
y_pred_catb=model_catb.predict(x_test)

print("Classification Report is \n",classification_report(y_test,y_pred_catb))

Classification Report is
               precision    recall  f1-score   support

           0       0.90      0.77      0.83      1033
           1       0.54      0.75      0.63       374

    accuracy                           0.77      1407
   macro avg       0.72      0.76      0.73      1407
weighted avg       0.80      0.77      0.78      1407

## **Optuna fine tuning**

In [151]:
def objective(trial):
    params={
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1),  
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), 
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'

    }

    model=XGBClassifier(**params)

    f1_scorer=make_scorer(f1_score,average='binary',pos_label=1)
    score=cross_val_score(model,x_train,y_train,cv=5,scoring=f1_scorer,n_jobs=-1).mean()

    return score
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)


print("Best parameters ",study.best_params)
print("best cv f1 score : ",study.best_value)


best_model_optuna=XGBClassifier(**study.best_params)
best_model_optuna.fit(x_train,y_train)
y_pred_optuna=best_model_optuna.predict(x_test)
print("Classification Report is : ",classification_report(y_test,y_pred_optuna))

[I 2026-03-19 23:19:43,730] A new study created in memory with name: no-name-5c366fe3-eb17-4114-87dc-1f6ffd7dcdb1
[I 2026-03-19 23:19:44,224] Trial 0 finished with value: 0.5924023968114851 and parameters: {'max_depth': 4, 'learning_rate': 0.02015959308567891, 'n_estimators': 617, 'subsample': 0.6673942505378271, 'colsample_bytree': 0.8796657562525987, 'min_child_weight': 10, 'gamma': 0.47434495316208763, 'reg_alpha': 0.8993350537933548, 'reg_lambda': 1.4495143803462762, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.5924023968114851.
[I 2026-03-19 23:19:44,903] Trial 1 finished with value: 0.538286664616256 and parameters: {'max_depth': 9, 'learning_rate': 0.10412280510660897, 'n_estimators': 576, 'subsample': 0.6507819168203691, 'colsample_bytree': 0.6873453088302044, 'min_child_weight': 1, 'gamma': 0.17340122352243031, 'reg_alpha': 0.43579321294601703, 'reg_lambda': 0.16381549640783266, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.5924023968114851.
[I 2026-03-19 23:19:45,170] Trial 2 finished with value: 0.6346463628453061 and parameters: {'max_depth': 3, 'learning_rate': 0.04984276253271492, 'n_estimators': 269, 'subsample': 0.9795702286503506, 'colsample_bytree': 0.8003417195683156, 'min_child_weight': 2, 'gamma': 0.1698284714372128, 'reg_alpha': 0.7583257344677153, 'reg_lambda': 0.9852603050682005, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:45,620] Trial 3 finished with value: 0.6166653217402123 and parameters: {'max_depth': 4, 'learning_rate': 0.06571406911337828, 'n_estimators': 643, 'subsample': 0.9166766555001151, 'colsample_bytree': 0.950387225163402, 'min_child_weight': 9, 'gamma': 0.35289217461664407, 'reg_alpha': 0.09914037357623717, 'reg_lambda': 0.8516914540331093, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:45,988] Trial 4 finished with value: 0.6242969247831472 and parameters: {'max_depth': 3, 'learning_rate': 0.03850770144355142, 'n_estimators': 558, 'subsample': 0.9945180420409914, 'colsample_bytree': 0.6387939948017158, 'min_child_weight': 9, 'gamma': 0.22386013401018862, 'reg_alpha': 0.019499160932849202, 'reg_lambda': 1.0763996333421844, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:47,104] Trial 5 finished with value: 0.5891287623126983 and parameters: {'max_depth': 8, 'learning_rate': 0.028356090456761567, 'n_estimators': 830, 'subsample': 0.6874052409138349, 'colsample_bytree': 0.9875589021001465, 'min_child_weight': 2, 'gamma': 0.38422609196938384, 'reg_alpha': 0.08345177525472447, 'reg_lambda': 1.2171768385681796, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:48,948] Trial 6 finished with value: 0.6013748575750636 and parameters: {'max_depth': 10, 'learning_rate': 0.011242736990890682, 'n_estimators': 894, 'subsample': 0.6111295962825182, 'colsample_bytree': 0.9290087939418531, 'min_child_weight': 1, 'gamma': 0.19007220356368498, 'reg_alpha': 0.2540009339289768, 'reg_lambda': 0.4209371682812544, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:49,670] Trial 7 finished with value: 0.5545523982935779 and parameters: {'max_depth': 4, 'learning_rate': 0.16266137039273318, 'n_estimators': 988, 'subsample': 0.8083203902249829, 'colsample_bytree': 0.7294001745940099, 'min_child_weight': 9, 'gamma': 0.25306894410241915, 'reg_alpha': 0.7103370626333381, 'reg_lambda': 0.7245043782433762, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:50,155] Trial 8 finished with value: 0.5879392376201038 and parameters: {'max_depth': 5, 'learning_rate': 0.02269088090234145, 'n_estimators': 552, 'subsample': 0.9023824341641872, 'colsample_bytree': 0.8654164123377588, 'min_child_weight': 7, 'gamma': 0.2962711620698731, 'reg_alpha': 0.7393197463592833, 'reg_lambda': 0.12761318263238852, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:50,452] Trial 9 finished with value: 0.6021362051247899 and parameters: {'max_depth': 6, 'learning_rate': 0.11604727890716934, 'n_estimators': 286, 'subsample': 0.653898837909115, 'colsample_bytree': 0.7178217412455906, 'min_child_weight': 6, 'gamma': 0.3137682293006091, 'reg_alpha': 0.3176930038126504, 'reg_lambda': 0.4556666467914481, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:50,657] Trial 10 finished with value: 0.5991097534391272 and parameters: {'max_depth': 7, 'learning_rate': 0.2240163786017669, 'n_estimators': 153, 'subsample': 0.9999576070864303, 'colsample_bytree': 0.7969901675731, 'min_child_weight': 4, 'gamma': 0.03716674046548957, 'reg_alpha': 0.693644215165177, 'reg_lambda': 1.952776837748977, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:50,922] Trial 11 finished with value: 0.6322159668624503 and parameters: {'max_depth': 3, 'learning_rate': 0.04327372262573752, 'n_estimators': 355, 'subsample': 0.9872484175971651, 'colsample_bytree': 0.6272747042302631, 'min_child_weight': 4, 'gamma': 0.10629201486159034, 'reg_alpha': 0.9903219228362428, 'reg_lambda': 1.2608238141614199, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:51,189] Trial 12 finished with value: 0.6299572327455192 and parameters: {'max_depth': 3, 'learning_rate': 0.05747501201471668, 'n_estimators': 345, 'subsample': 0.9021639212736974, 'colsample_bytree': 0.8128982003495029, 'min_child_weight': 4, 'gamma': 0.08184594277195553, 'reg_alpha': 0.9162205769724621, 'reg_lambda': 1.5205270826560566, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:51,558] Trial 13 finished with value: 0.6183070094245202 and parameters: {'max_depth': 6, 'learning_rate': 0.0385664274765205, 'n_estimators': 343, 'subsample': 0.8071734987603211, 'colsample_bytree': 0.6000674997465811, 'min_child_weight': 3, 'gamma': 0.12924733376389005, 'reg_alpha': 0.9758537828493048, 'reg_lambda': 1.4034790145617886, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:51,678] Trial 14 finished with value: 0.6334846627827735 and parameters: {'max_depth': 3, 'learning_rate': 0.0793395571130273, 'n_estimators': 100, 'subsample': 0.9469852392235225, 'colsample_bytree': 0.786688439524813, 'min_child_weight': 4, 'gamma': 0.003619387543261507, 'reg_alpha': 0.5902080721769106, 'reg_lambda': 1.7823918875868339, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:51,859] Trial 15 finished with value: 0.6245234931916517 and parameters: {'max_depth': 5, 'learning_rate': 0.07811152722739685, 'n_estimators': 149, 'subsample': 0.9365091852816554, 'colsample_bytree': 0.7851044786241428, 'min_child_weight': 6, 'gamma': 0.019092082072220018, 'reg_alpha': 0.5733541779417937, 'reg_lambda': 1.856764320186976, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:52,001] Trial 16 finished with value: 0.6219863780311 and parameters: {'max_depth': 5, 'learning_rate': 0.10382354444359551, 'n_estimators': 107, 'subsample': 0.8493745145169165, 'colsample_bytree': 0.8416725248935026, 'min_child_weight': 3, 'gamma': 0.01619997272758663, 'reg_alpha': 0.545930046604487, 'reg_lambda': 1.6334483896994965, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:52,207] Trial 17 finished with value: 0.6060388230337587 and parameters: {'max_depth': 3, 'learning_rate': 0.29156723054808215, 'n_estimators': 222, 'subsample': 0.7451952174891502, 'colsample_bytree': 0.7627227999525553, 'min_child_weight': 5, 'gamma': 0.15257157946051864, 'reg_alpha': 0.788203333548157, 'reg_lambda': 0.7778231867678402, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:52,808] Trial 18 finished with value: 0.5851290843835303 and parameters: {'max_depth': 7, 'learning_rate': 0.013867671417421321, 'n_estimators': 424, 'subsample': 0.8631374568795414, 'colsample_bytree': 0.7458351897494255, 'min_child_weight': 2, 'gamma': 0.07751949405014841, 'reg_alpha': 0.6031529124402936, 'reg_lambda': 1.6985453299415265, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:53,129] Trial 19 finished with value: 0.6134386434144359 and parameters: {'max_depth': 4, 'learning_rate': 0.16321211634770638, 'n_estimators': 440, 'subsample': 0.9587369288406218, 'colsample_bytree': 0.6839881219300653, 'min_child_weight': 7, 'gamma': 0.4921144878831525, 'reg_alpha': 0.42334741602925313, 'reg_lambda': 1.0054946146878216, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:53,363] Trial 20 finished with value: 0.6144212622969658 and parameters: {'max_depth': 5, 'learning_rate': 0.08099944483747842, 'n_estimators': 210, 'subsample': 0.8509688500776129, 'colsample_bytree': 0.889990563219143, 'min_child_weight': 2, 'gamma': 0.23345522669755014, 'reg_alpha': 0.8515174309614975, 'reg_lambda': 0.549601992654263, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:53,676] Trial 21 finished with value: 0.6265778415125246 and parameters: {'max_depth': 3, 'learning_rate': 0.04580342866116452, 'n_estimators': 433, 'subsample': 0.9553779219409559, 'colsample_bytree': 0.6556351141799159, 'min_child_weight': 4, 'gamma': 0.09154671417240512, 'reg_alpha': 0.9821676930869647, 'reg_lambda': 1.2713914293451327, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:53,901] Trial 22 finished with value: 0.6299539881076706 and parameters: {'max_depth': 3, 'learning_rate': 0.03287053494944396, 'n_estimators': 264, 'subsample': 0.9639014559990092, 'colsample_bytree': 0.8318317689881156, 'min_child_weight': 5, 'gamma': 0.10196456978034933, 'reg_alpha': 0.6252527808583478, 'reg_lambda': 1.1621163100239982, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:54,187] Trial 23 finished with value: 0.6263489129786304 and parameters: {'max_depth': 4, 'learning_rate': 0.05493206088118932, 'n_estimators': 353, 'subsample': 0.9981968114821239, 'colsample_bytree': 0.7751639917439616, 'min_child_weight': 3, 'gamma': 0.05632033301593394, 'reg_alpha': 0.8043313119279012, 'reg_lambda': 1.7259024637500593, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:54,371] Trial 24 finished with value: 0.6331913051752716 and parameters: {'max_depth': 3, 'learning_rate': 0.0249745703860052, 'n_estimators': 194, 'subsample': 0.8742719229531009, 'colsample_bytree': 0.6014908044774124, 'min_child_weight': 4, 'gamma': 0.14549817843922236, 'reg_alpha': 0.477016917717025, 'reg_lambda': 1.3232308336028247, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:54,555] Trial 25 finished with value: 0.6283623377398697 and parameters: {'max_depth': 4, 'learning_rate': 0.020081692758415284, 'n_estimators': 173, 'subsample': 0.8768993939676735, 'colsample_bytree': 0.9033908082732639, 'min_child_weight': 3, 'gamma': 0.1522806783544237, 'reg_alpha': 0.4843156189334645, 'reg_lambda': 0.976387162654732, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:54,696] Trial 26 finished with value: 0.5643265483878532 and parameters: {'max_depth': 3, 'learning_rate': 0.026089606005647373, 'n_estimators': 127, 'subsample': 0.7483259109400872, 'colsample_bytree': 0.69021743157171, 'min_child_weight': 5, 'gamma': 0.18864845333972885, 'reg_alpha': 0.32623097323578226, 'reg_lambda': 1.998584592481628, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:55,037] Trial 27 finished with value: 0.6263272850535253 and parameters: {'max_depth': 6, 'learning_rate': 0.01672276197096236, 'n_estimators': 263, 'subsample': 0.9287191983921961, 'colsample_bytree': 0.8365741026521483, 'min_child_weight': 2, 'gamma': 0.27093617663852676, 'reg_alpha': 0.649458590478004, 'reg_lambda': 1.5628745943858797, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:55,692] Trial 28 finished with value: 0.5954381874963158 and parameters: {'max_depth': 5, 'learning_rate': 0.07244233827720327, 'n_estimators': 715, 'subsample': 0.8884936745938149, 'colsample_bytree': 0.7159403168081092, 'min_child_weight': 1, 'gamma': 0.21705295675218023, 'reg_alpha': 0.5183269577177262, 'reg_lambda': 1.8154729479106648, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:55,887] Trial 29 finished with value: 0.5968719281080318 and parameters: {'max_depth': 4, 'learning_rate': 0.04945373695640509, 'n_estimators': 198, 'subsample': 0.8315671794986845, 'colsample_bytree': 0.8706928405206021, 'min_child_weight': 6, 'gamma': 0.4257546521033868, 'reg_alpha': 0.45273884786081886, 'reg_lambda': 1.4041251597206221, 'scale_pos_weight': 1}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:56,214] Trial 30 finished with value: 0.633657786842994 and parameters: {'max_depth': 3, 'learning_rate': 0.03105109077620505, 'n_estimators': 476, 'subsample': 0.9361756441417987, 'colsample_bytree': 0.6041786592084983, 'min_child_weight': 3, 'gamma': 0.13628869092425688, 'reg_alpha': 0.33573851111853836, 'reg_lambda': 1.40381558204637, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:56,674] Trial 31 finished with value: 0.6320732360503367 and parameters: {'max_depth': 3, 'learning_rate': 0.031216266899536667, 'n_estimators': 493, 'subsample': 0.9369190932841863, 'colsample_bytree': 0.6034094357812109, 'min_child_weight': 3, 'gamma': 0.1399165003600646, 'reg_alpha': 0.3844150397355862, 'reg_lambda': 1.3793267483898801, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 2 with value: 0.6346463628453061.
[I 2026-03-19 23:19:56,911] Trial 32 finished with value: 0.6357847665144231 and parameters: {'max_depth': 4, 'learning_rate': 0.021326169935095604, 'n_estimators': 280, 'subsample': 0.9592650404299282, 'colsample_bytree': 0.6719660122516147, 'min_child_weight': 4, 'gamma': 0.0038501484684124515, 'reg_alpha': 0.20335792547951695, 'reg_lambda': 1.4999513838437746, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:19:57,419] Trial 33 finished with value: 0.6327057940147257 and parameters: {'max_depth': 4, 'learning_rate': 0.01609771014247012, 'n_estimators': 679, 'subsample': 0.9757801685051093, 'colsample_bytree': 0.6490470027921893, 'min_child_weight': 2, 'gamma': 0.0021894049919169256, 'reg_alpha': 0.18038640143725654, 'reg_lambda': 1.5115248531695178, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:19:57,788] Trial 34 finished with value: 0.633565052340977 and parameters: {'max_depth': 4, 'learning_rate': 0.019562821573606143, 'n_estimators': 483, 'subsample': 0.9528845056582131, 'colsample_bytree': 0.6700706979680338, 'min_child_weight': 1, 'gamma': 0.0493949545782221, 'reg_alpha': 0.24649107300675321, 'reg_lambda': 1.1071725170485744, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:19:58,200] Trial 35 finished with value: 0.6348316895713367 and parameters: {'max_depth': 4, 'learning_rate': 0.010025127186275788, 'n_estimators': 484, 'subsample': 0.9252776115060923, 'colsample_bytree': 0.683903560026339, 'min_child_weight': 1, 'gamma': 0.05622484823450407, 'reg_alpha': 0.20595149778312327, 'reg_lambda': 0.8906022508106584, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:19:59,358] Trial 36 finished with value: 0.5771385816955599 and parameters: {'max_depth': 10, 'learning_rate': 0.0101963871415006, 'n_estimators': 587, 'subsample': 0.9092605434772153, 'colsample_bytree': 0.6290103817270655, 'min_child_weight': 1, 'gamma': 0.06381084009465199, 'reg_alpha': 0.1542857163703738, 'reg_lambda': 0.9469947463278626, 'scale_pos_weight': 1}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:20:00,753] Trial 37 finished with value: 0.6091934127495595 and parameters: {'max_depth': 9, 'learning_rate': 0.01363002036116235, 'n_estimators': 779, 'subsample': 0.9195947132634265, 'colsample_bytree': 0.7012532403408658, 'min_child_weight': 2, 'gamma': 0.12172817432348657, 'reg_alpha': 0.046140881513009185, 'reg_lambda': 0.846215382825744, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:20:01,123] Trial 38 finished with value: 0.6285353539067913 and parameters: {'max_depth': 4, 'learning_rate': 0.03557845222480154, 'n_estimators': 492, 'subsample': 0.9729688409867497, 'colsample_bytree': 0.7501773345721783, 'min_child_weight': 1, 'gamma': 0.17783067065294406, 'reg_alpha': 0.2031104510313148, 'reg_lambda': 1.085400613019233, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:20:01,453] Trial 39 finished with value: 0.5809195560966416 and parameters: {'max_depth': 5, 'learning_rate': 0.01188915719428726, 'n_estimators': 307, 'subsample': 0.7683762974781656, 'colsample_bytree': 0.6643491500271006, 'min_child_weight': 2, 'gamma': 0.20816319241000772, 'reg_alpha': 0.31983276464094207, 'reg_lambda': 0.6374975082414026, 'scale_pos_weight': 1}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:20:02,102] Trial 40 finished with value: 0.6194470520114519 and parameters: {'max_depth': 8, 'learning_rate': 0.02901262795717152, 'n_estimators': 597, 'subsample': 0.6868205674573373, 'colsample_bytree': 0.6253542283436481, 'min_child_weight': 10, 'gamma': 0.033279311731276975, 'reg_alpha': 0.12074873914053919, 'reg_lambda': 0.9115080328874797, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:20:02,504] Trial 41 finished with value: 0.6332698482311576 and parameters: {'max_depth': 4, 'learning_rate': 0.01935550194231184, 'n_estimators': 531, 'subsample': 0.9752802062720414, 'colsample_bytree': 0.6760304755642431, 'min_child_weight': 1, 'gamma': 0.03673576664979489, 'reg_alpha': 0.260033477842643, 'reg_lambda': 1.0389198359073157, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.
[I 2026-03-19 23:20:02,842] Trial 42 finished with value: 0.634249932218222 and parameters: {'max_depth': 4, 'learning_rate': 0.02219156979107574, 'n_estimators': 409, 'subsample': 0.9407867416007999, 'colsample_bytree': 0.7368263032512613, 'min_child_weight': 1, 'gamma': 0.06348936212762421, 'reg_alpha': 0.2220233996523486, 'reg_lambda': 1.154522557268716, 'scale_pos_weight': np.float64(2.762541806020067)}. Best is trial 32 with value: 0.6357847665144231.

Best parameters  {'max_depth': 4, 'learning_rate': 0.021326169935095604, 'n_estimators': 280, 'subsample': 0.9592650404299282, 'colsample_bytree': 0.6719660122516147, 'min_child_weight': 4, 'gamma': 0.0038501484684124515, 'reg_alpha': 0.20335792547951695, 'reg_lambda': 1.4999513838437746, 'scale_pos_weight': np.float64(2.762541806020067)}
best cv f1 score :  0.6357847665144231
Classification Report is :                precision    recall  f1-score   support

           0       0.91      0.73      0.81      1033
           1       0.52      0.80      0.63       374

    accuracy                           0.75      1407
   macro avg       0.72      0.77      0.72      1407
weighted avg       0.81      0.75      0.76      1407

In [152]:
joblib.dump(best_model_optuna,"../models/best_optuna_churn_model.pkl")
print("Model is saved as best_optuna_model.pkl")

Model is saved as best_optuna_model.pkl

In [153]:
joblib.dump(model_ada_weighted,"../models/best_adaboost_churn_model.pkl")
print("Model is saved as best_adaboost.pkl")

Model is saved as best_adaboost.pkl