## Importing Libraries

In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE,ADASYN
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score,make_scorer
from sklearn.tree import  DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV,cross_val_score
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from collections import Counter
import joblib
import warnings
import optuna

## Model's Object Names

In [55]:
warnings.filterwarnings('ignore')
scaler=StandardScaler()
smoteenn=SMOTEENN()
smote=SMOTE(random_state=42)
adaysn=ADASYN(random_state=42)
minmax=MinMaxScaler()
model_dt=DecisionTreeClassifier()
model_rf=RandomForestClassifier(n_estimators=50)
model_xgb=XGBClassifier(random_state=42)
model_rfp=RandomForestClassifier(class_weight='balanced',random_state=42,n_estimators=300,max_depth=6)
model_cat=CatBoostClassifier(auto_class_weights='Balanced',random_state=42,verbose=0)
model_xgb_hyper=XGBClassifier(random_state=42,eval_metric='logloss')

In [56]:
df=pd.read_csv('./dataset/Customer-Churn.csv')

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.Churn.value_counts()/len(df.Churn)*100

Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

In [6]:
y=df['Churn']
x=df.drop(columns=['Churn','customerID'])

In [7]:
print("shape of x is : ",x.shape)

shape of x is :  (7043, 19)

In [8]:
print("shape of y :",y.shape)

shape of y : (7043,)

In [9]:
x=pd.get_dummies(data=x,drop_first=True)
y=df['Churn'].map({"Yes":1,"No":0})
x

,SeniorCitizen,tenure,MonthlyCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,TotalCharges_995.35,TotalCharges_996.45,TotalCharges_996.85,TotalCharges_996.95,TotalCharges_997.65,TotalCharges_997.75,TotalCharges_998.1,TotalCharges_999.45,TotalCharges_999.8,TotalCharges_999.9
0,0,1,29.85,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,0,34,56.95,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0,2,53.85,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0,45,42.30,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,0,2,70.70,False,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,True,True,True,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
7039,0,72,103.20,False,True,True,True,False,True,True,...,False,False,False,False,False,False,False,False,False,False
7040,0,11,29.60,False,True,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,1,4,74.40,True,True,False,True,False,True,True,...,False,False,False,False,False,False,False,False,False,False
7042,0,66,105.65,True,False,False,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:

model_dt.fit(x_train,y_train)
model_dt1_y_pred=model_dt.predict(x_test)
print(classification_report(y_test,model_dt1_y_pred))

              precision    recall  f1-score   support

           0       0.84      0.85      0.85      1058
           1       0.53      0.52      0.53       351

    accuracy                           0.77      1409
   macro avg       0.69      0.69      0.69      1409
weighted avg       0.77      0.77      0.77      1409

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [13]:
df_copy=df.copy()

In [14]:
df_copy['TotalCharges']=pd.to_numeric(df_copy.TotalCharges,errors='coerce')

In [15]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [16]:
df_copy.loc[df_copy['TotalCharges'].isnull()==True]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [17]:
df_copy.dropna(how='any',inplace=True)

In [18]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [19]:
df_copy.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [20]:
bins=[0,12,24,36,48,60,72]
labels=['1-12','13-24','25-36','37-48','49-60','61-72']
df_copy['tenure_bin']=pd.cut(df_copy['tenure'],bins=bins,labels=labels,include_lowest=True)

In [21]:
df_copy[['tenure','tenure_bin']].head(10)

   tenure tenure_bin
0       1       1-12
1      34      25-36
2       2       1-12
3      45      37-48
4       2       1-12
5       8       1-12
6      22      13-24
7      10       1-12
8      28      25-36
9      62      61-72

In [22]:
df_copy['tenure_bin'].value_counts().sort_index()

tenure_bin
1-12     2175
13-24    1024
25-36     832
37-48     762
49-60     832
61-72    1407
Name: count, dtype: int64

In [23]:
df_copy.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_bin
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1-12
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,25-36
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1-12
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,37-48
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1-12

In [24]:
y=df_copy['Churn']
x=df_copy.drop(columns=['customerID','tenure','Churn'])

print("Shape of X is :",x.shape)
print("Shape of Y is :",y.shape)

Shape of X is : (7032, 19)
Shape of Y is : (7032,)

In [25]:
x=pd.get_dummies(x,drop_first=True)
y=df_copy['Churn'].map({'Yes':1,'No':0})

In [26]:
x

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_bin_13-24,tenure_bin_25-36,tenure_bin_37-48,tenure_bin_49-60,tenure_bin_61-72
0,0,29.85,29.85,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
1,0,56.95,1889.50,True,False,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
2,0,53.85,108.15,True,False,False,True,False,False,False,...,False,True,False,False,True,False,False,False,False,False
3,0,42.30,1840.75,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,70.70,151.65,False,False,False,True,False,False,True,...,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,84.80,1990.50,True,True,True,True,False,True,False,...,False,True,False,False,True,True,False,False,False,False
7039,0,103.20,7362.90,False,True,True,True,False,True,True,...,False,True,True,False,False,False,False,False,False,True
7040,0,29.60,346.45,False,True,True,False,True,False,False,...,False,True,False,True,False,False,False,False,False,False
7041,1,74.40,306.60,True,True,False,True,False,True,True,...,False,True,False,False,True,False,False,False,False,False
7042,0,105.65,6844.50,True,False,False,True,False,False,True,...,True,True,False,False,False,False,False,False,False,True

## Train Test Split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Feature Scaling - StandardScaler

In [28]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

## DescionTree

In [29]:
model_dt.fit(x_train,y_train)
model_dt2_y_pred=model_dt.predict(x_test)
print(classification_report(y_test,model_dt2_y_pred))

              precision    recall  f1-score   support

           0       0.81      0.80      0.81      1024
           1       0.48      0.50      0.49       383

    accuracy                           0.72      1407
   macro avg       0.65      0.65      0.65      1407
weighted avg       0.72      0.72      0.72      1407

## Feature Scaling - MinMaxScaler

In [30]:
x_train_mns=minmax.fit_transform(x_train)
y_train_mns=minmax.transform(x_test)

## DescionTree With MIN MAX

In [31]:
model_dt.fit(x_train_mns,y_train)
model_dt3_y_pred=model_dt.predict(x_test)
print(classification_report(y_test,model_dt3_y_pred))

              precision    recall  f1-score   support

           0       0.81      0.64      0.72      1024
           1       0.38      0.60      0.47       383

    accuracy                           0.63      1407
   macro avg       0.60      0.62      0.59      1407
weighted avg       0.69      0.63      0.65      1407

## DescionTree With SMOTENN

In [32]:
x_train_smotenn,y_train_smotenn=smoteenn.fit_resample(x_train,y_train)
model_dt.fit(x_train_smotenn,y_train_smotenn)
model_dt4_y_pred=model_dt.predict(x_test)
print(classification_report(y_test,model_dt4_y_pred))

              precision    recall  f1-score   support

           0       0.88      0.71      0.79      1024
           1       0.49      0.74      0.59       383

    accuracy                           0.72      1407
   macro avg       0.68      0.73      0.69      1407
weighted avg       0.77      0.72      0.73      1407

## RandomForest With SMOTENN

In [33]:
model_rf.fit(x_train_smotenn,y_train_smotenn)
model_rf1_y_pred=model_rf.predict(x_test)
print(classification_report(y_test,model_rf1_y_pred))

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1024
           1       0.51      0.78      0.62       383

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.71      1407
weighted avg       0.79      0.73      0.75      1407

## Xgboost Without SMOTENN

In [34]:
model_xgb.fit(x_train,y_train)
model_xgb1_y_pred=model_xgb.predict(x_test)
print(classification_report(y_test,model_xgb1_y_pred))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1024
           1       0.62      0.50      0.55       383

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407

## Xgboost With SMOTENN

In [35]:
model_xgb.fit(x_train_smotenn,y_train_smotenn)
model_xgb2_y_pred=model_xgb.predict(x_test)
print(classification_report(y_test,model_xgb2_y_pred))

              precision    recall  f1-score   support

           0       0.89      0.72      0.80      1024
           1       0.51      0.76      0.61       383

    accuracy                           0.73      1407
   macro avg       0.70      0.74      0.70      1407
weighted avg       0.79      0.73      0.75      1407

##  Xgboost With SMOTE

In [36]:
x_train_smote,y_train_smote=smote.fit_resample(x_train,y_train)
print("Before smote",Counter(y_train))
print("After smote",Counter(y_train_smote))
model_xgb.fit(x_train_smote,y_train_smote)
model_xgb3_y_pred=model_xgb.predict(x_test)
print(classification_report(y_test,model_xgb3_y_pred))

Before smote Counter({0: 4139, 1: 1486})
After smote Counter({0: 4139, 1: 4139})
              precision    recall  f1-score   support

           0       0.84      0.85      0.84      1024
           1       0.58      0.56      0.57       383

    accuracy                           0.77      1407
   macro avg       0.71      0.70      0.71      1407
weighted avg       0.77      0.77      0.77      1407

## Xgboost With ADAYSN

In [37]:
x_train_adaysn,y_train_adaysn=adaysn.fit_resample(x_train,y_train)
print("Before adaysn : ",Counter(y_train))
print("After adaysn : ",Counter(y_train_adaysn))
model_xgb.fit(x_train_adaysn,y_train_adaysn)
model_xgb4_y_pred=model_xgb.predict(x_test)
print(accuracy_score(y_test,model_xgb4_y_pred))
print(classification_report(y_test,model_xgb4_y_pred))
print(confusion_matrix(y_test,model_xgb4_y_pred))

Before adaysn :  Counter({0: 4139, 1: 1486})
After adaysn :  Counter({0: 4139, 1: 4058})
0.7683013503909026
              precision    recall  f1-score   support

           0       0.83      0.85      0.84      1024
           1       0.58      0.55      0.56       383

    accuracy                           0.77      1407
   macro avg       0.71      0.70      0.70      1407
weighted avg       0.76      0.77      0.77      1407

[[872 152]
 [174 209]]

## Xgboost With Scale_Pos_Weight

In [38]:
scale_pos_weight=(y_train==0).sum()/(y_train==1).sum()
print("Scale Pos Weight is :",scale_pos_weight)
model_xgb_scale_poss_weight=XGBClassifier(scale_pos_weight=scale_pos_weight,eval_metric='logloss',random_state=42)
model_xgb_scale_poss_weight.fit(x_train,y_train)
model_xgb5_y_pred=model_xgb_scale_poss_weight.predict(x_test)
print(accuracy_score(y_test,model_xgb5_y_pred))
print(classification_report(y_test,model_xgb5_y_pred))
print(confusion_matrix(y_test,model_xgb5_y_pred))

Scale Pos Weight is : 2.785329744279946
0.757640369580668
              precision    recall  f1-score   support

           0       0.86      0.80      0.83      1024
           1       0.55      0.65      0.59       383

    accuracy                           0.76      1407
   macro avg       0.70      0.72      0.71      1407
weighted avg       0.77      0.76      0.76      1407

[[817 207]
 [134 249]]

## Random Forest With Parameters

In [39]:
model_rfp.fit(x_train,y_train)
model_rfp1_y_pred=model_rfp.predict(x_test)
print(classification_report(y_test,model_rfp1_y_pred))

              precision    recall  f1-score   support

           0       0.90      0.71      0.80      1024
           1       0.51      0.78      0.61       383

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.75      1407

## CatBoost With Parameters

In [40]:
model_cat.fit(x_train,y_train)
model_cat_y_pred=model_cat.predict(x_test)
print(classification_report(y_test,model_cat_y_pred))

              precision    recall  f1-score   support

           0       0.88      0.78      0.82      1024
           1       0.54      0.71      0.62       383

    accuracy                           0.76      1407
   macro avg       0.71      0.74      0.72      1407
weighted avg       0.79      0.76      0.77      1407

## Light GBM With Scale_Pos_Weight

In [41]:
model_lgbm=LGBMClassifier(random_state=42,scale_pos_weight=scale_pos_weight)
model_lgbm.fit(x_train,y_train)
model_lgbm1_y_pred=model_lgbm.predict(x_test)
print(classification_report(y_test,model_lgbm1_y_pred))

[LightGBM] [Info] Number of positive: 1486, number of negative: 4139
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001023 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 606
[LightGBM] [Info] Number of data points in the train set: 5625, number of used features: 34
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.264178 -> initscore=-1.024366
[LightGBM] [Info] Start training from score -1.024366
              precision    recall  f1-score   support

           0       0.88      0.77      0.82      1024
           1       0.54      0.73      0.62       383

    accuracy                           0.76      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.76      0.77      1407

## Adaboost with Sample Weight

In [42]:
negative_count=(y_train==0).sum()
positive_count=(y_train==1).sum()
np_weight=negative_count/positive_count

sample_weight=np.where(y_train==1,np_weight,1.0)

model_ada_weighted=AdaBoostClassifier(n_estimators=50,random_state=42)

model_ada_weighted.fit(x_train,y_train,sample_weight=sample_weight)

y_pred_ada_weighted=model_ada_weighted.predict(x_test)


print("Accuracy Score is : ",accuracy_score(y_pred_ada_weighted,y_test))
print("Classification Report is : \n",classification_report(y_pred_ada_weighted,y_test))
print("Confusion Matrix \n",confusion_matrix(y_pred_ada_weighted,y_test))

Accuracy Score is :  0.746268656716418
Classification Report is :
               precision    recall  f1-score   support

           0       0.74      0.89      0.81       849
           1       0.76      0.52      0.62       558

    accuracy                           0.75      1407
   macro avg       0.75      0.71      0.72      1407
weighted avg       0.75      0.75      0.73      1407

Confusion Matrix
 [[758  91]
 [266 292]]

In [43]:
param_grid={
    'max_depth': [3, 4, 5, 6, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'n_estimators': [100, 200, 300, 400],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.2],
    'scale_pos_weight': [1, scale_pos_weight]  # try both balanced and weighted
}
random_search=RandomizedSearchCV(model_xgb_hyper,param_grid,random_state=42,scoring='f1',n_jobs=-1,cv=5,n_iter=50)

random_search.fit(x_train,y_train)


print("Best Parameters : ",random_search.best_params_)
print("best f1 score is : ",random_search.best_score_)

best_model=random_search.best_estimator_
y_pred_best=best_model.predict(x_test)

print("\n Test Classifiction Report \n ",classification_report(y_pred_best,y_test))

Best Parameters :  {'subsample': 0.8, 'scale_pos_weight': np.float64(2.785329744279946), 'n_estimators': 200, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.05, 'gamma': 0.2, 'colsample_bytree': 0.8}
best f1 score is :  0.6277556973527989

 Test Classifiction Report
                precision    recall  f1-score   support

           0       0.74      0.89      0.81       852
           1       0.76      0.52      0.62       555

    accuracy                           0.75      1407
   macro avg       0.75      0.71      0.72      1407
weighted avg       0.75      0.75      0.74      1407

In [44]:
joblib.dump(best_model,"./models/best_xgboost_model.pkl")
print("Model is Saved Succesfully")

Model is Saved Succesfully

In [50]:
def objective(trial):
    params={
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 1), 
        'reg_lambda': trial.suggest_float('reg_lambda', 0, 2), 
        'scale_pos_weight': trial.suggest_categorical('scale_pos_weight', [1, scale_pos_weight]),
        'random_state': 42,
        'eval_metric': 'logloss'
    }
    model=XGBClassifier(**params)

    f1_scoreer=make_scorer(f1_score,average='binary',pos_label=1)
    score=cross_val_score(model,x_train,y_train,cv=5,scoring=f1_scoreer,n_jobs=-1).mean()

    return score
study=optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=100)

print("Best params are ",study.best_params)
print("best score is :",study.best_value)

best_optuna_model=XGBClassifier(**study.best_params)
best_optuna_model.fit(x_train,y_train)
y_pred_optuna=best_optuna_model.predict(x_test)
print("classification_report is \n : ",classification_report(y_test,y_pred_optuna))

[I 2026-03-06 22:45:30,144] A new study created in memory with name: no-name-5bceb019-ae6c-48ce-a1af-b087977b91f8
[I 2026-03-06 22:45:31,154] Trial 0 finished with value: 0.6192958691423083 and parameters: {'max_depth': 3, 'learning_rate': 0.055032685642513866, 'n_estimators': 902, 'subsample': 0.8319135686809065, 'colsample_bytree': 0.6609391728804548, 'min_child_weight': 7, 'gamma': 0.37244775674427766, 'reg_alpha': 0.3215244399205798, 'reg_lambda': 1.95632699457203, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 0 with value: 0.6192958691423083.
[I 2026-03-06 22:45:32,083] Trial 1 finished with value: 0.6082500971212775 and parameters: {'max_depth': 6, 'learning_rate': 0.062227253828817164, 'n_estimators': 639, 'subsample': 0.9450701768080566, 'colsample_bytree': 0.9910818289284338, 'min_child_weight': 9, 'gamma': 0.46428923831163615, 'reg_alpha': 0.11113608043043055, 'reg_lambda': 0.32493526910338644, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 0 with value: 0.6192958691423083.
[I 2026-03-06 22:45:32,476] Trial 2 finished with value: 0.6175422105601134 and parameters: {'max_depth': 6, 'learning_rate': 0.08134898769578973, 'n_estimators': 127, 'subsample': 0.7975668105848963, 'colsample_bytree': 0.6331476745286518, 'min_child_weight': 5, 'gamma': 0.21111305040422879, 'reg_alpha': 0.42033610932630916, 'reg_lambda': 0.5532774228108712, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 0 with value: 0.6192958691423083.
[I 2026-03-06 22:45:33,342] Trial 3 finished with value: 0.6055549736654227 and parameters: {'max_depth': 6, 'learning_rate': 0.040205347589078434, 'n_estimators': 454, 'subsample': 0.8466378291387423, 'colsample_bytree': 0.7725390754970204, 'min_child_weight': 3, 'gamma': 0.48701219466747325, 'reg_alpha': 0.9241940512669832, 'reg_lambda': 1.4081372698259507, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 0 with value: 0.6192958691423083.
[I 2026-03-06 22:45:34,092] Trial 4 finished with value: 0.5714485757140662 and parameters: {'max_depth': 5, 'learning_rate': 0.09408031752339566, 'n_estimators': 480, 'subsample': 0.8505023275710614, 'colsample_bytree': 0.8981318614827749, 'min_child_weight': 10, 'gamma': 0.004612968245726268, 'reg_alpha': 0.06511235825945716, 'reg_lambda': 0.6822470686433719, 'scale_pos_weight': 1}. Best is trial 0 with value: 0.6192958691423083.
[I 2026-03-06 22:45:34,906] Trial 5 finished with value: 0.6284817713670061 and parameters: {'max_depth': 3, 'learning_rate': 0.010466941660929829, 'n_estimators': 439, 'subsample': 0.697799817012102, 'colsample_bytree': 0.7305634158340973, 'min_child_weight': 10, 'gamma': 0.4704257088733879, 'reg_alpha': 0.19257896531518703, 'reg_lambda': 1.0851726513846847, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:36,088] Trial 6 finished with value: 0.5853274659739762 and parameters: {'max_depth': 7, 'learning_rate': 0.017231441667959622, 'n_estimators': 552, 'subsample': 0.9800908018926593, 'colsample_bytree': 0.9655609233740505, 'min_child_weight': 4, 'gamma': 0.15222929085765552, 'reg_alpha': 0.8595020704463632, 'reg_lambda': 0.6743426130846077, 'scale_pos_weight': 1}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:37,154] Trial 7 finished with value: 0.5696557825698977 and parameters: {'max_depth': 7, 'learning_rate': 0.09118059813080277, 'n_estimators': 480, 'subsample': 0.600485693980569, 'colsample_bytree': 0.6221149447228831, 'min_child_weight': 8, 'gamma': 0.23895132562271226, 'reg_alpha': 0.4559371562511215, 'reg_lambda': 1.5872526099250934, 'scale_pos_weight': 1}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:37,548] Trial 8 finished with value: 0.5894367517154112 and parameters: {'max_depth': 5, 'learning_rate': 0.03862010034727561, 'n_estimators': 136, 'subsample': 0.7827903947119652, 'colsample_bytree': 0.9417916813639677, 'min_child_weight': 3, 'gamma': 0.2646021548619379, 'reg_alpha': 0.1002195181781752, 'reg_lambda': 1.5508563418340113, 'scale_pos_weight': 1}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:38,174] Trial 9 finished with value: 0.6270139452419137 and parameters: {'max_depth': 9, 'learning_rate': 0.022517548093593565, 'n_estimators': 181, 'subsample': 0.6282533613017526, 'colsample_bytree': 0.6141608757704744, 'min_child_weight': 5, 'gamma': 0.25965521805792163, 'reg_alpha': 0.17318115681717505, 'reg_lambda': 0.9622528421251604, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:39,144] Trial 10 finished with value: 0.5827039742851443 and parameters: {'max_depth': 3, 'learning_rate': 0.27870907163480485, 'n_estimators': 784, 'subsample': 0.7099744305875039, 'colsample_bytree': 0.7588346542735237, 'min_child_weight': 1, 'gamma': 0.3856258741217531, 'reg_alpha': 0.6685552436347095, 'reg_lambda': 0.044122764333856646, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:39,945] Trial 11 finished with value: 0.627345802084789 and parameters: {'max_depth': 10, 'learning_rate': 0.010548551348047833, 'n_estimators': 254, 'subsample': 0.625302292437853, 'colsample_bytree': 0.6982455814433787, 'min_child_weight': 6, 'gamma': 0.0798481238719625, 'reg_alpha': 0.2560325680037749, 'reg_lambda': 1.0833609936177262, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:41,031] Trial 12 finished with value: 0.6270484154154781 and parameters: {'max_depth': 10, 'learning_rate': 0.010403970999774356, 'n_estimators': 321, 'subsample': 0.692406941091368, 'colsample_bytree': 0.7135606930135002, 'min_child_weight': 7, 'gamma': 0.04172601125788002, 'reg_alpha': 0.2629362061792053, 'reg_lambda': 1.1168904224044147, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:41,935] Trial 13 finished with value: 0.6269210813166398 and parameters: {'max_depth': 9, 'learning_rate': 0.01121655422895992, 'n_estimators': 312, 'subsample': 0.6788777912985683, 'colsample_bytree': 0.8243664570117765, 'min_child_weight': 10, 'gamma': 0.10088229792502235, 'reg_alpha': 0.5564160050422133, 'reg_lambda': 1.030152467498164, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:42,767] Trial 14 finished with value: 0.625516483908137 and parameters: {'max_depth': 8, 'learning_rate': 0.019372292314044973, 'n_estimators': 306, 'subsample': 0.7317459832327938, 'colsample_bytree': 0.7101853001878604, 'min_child_weight': 7, 'gamma': 0.3289212940260853, 'reg_alpha': 0.2728693092588465, 'reg_lambda': 1.2570166846198325, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:43,739] Trial 15 finished with value: 0.6275874245382131 and parameters: {'max_depth': 4, 'learning_rate': 0.014267506360225857, 'n_estimators': 662, 'subsample': 0.6520217415751528, 'colsample_bytree': 0.8249247188717737, 'min_child_weight': 1, 'gamma': 0.13843356567281634, 'reg_alpha': 0.0007706933586229536, 'reg_lambda': 0.8983566141075074, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:44,711] Trial 16 finished with value: 0.6191814088892252 and parameters: {'max_depth': 4, 'learning_rate': 0.028442094801789365, 'n_estimators': 698, 'subsample': 0.7466193269370113, 'colsample_bytree': 0.8248766279396231, 'min_child_weight': 1, 'gamma': 0.16387721160521634, 'reg_alpha': 0.019885175880572065, 'reg_lambda': 0.8347186999823604, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:46,026] Trial 17 finished with value: 0.5751476341336765 and parameters: {'max_depth': 4, 'learning_rate': 0.17383570385436528, 'n_estimators': 972, 'subsample': 0.662476349404735, 'colsample_bytree': 0.8736410772634499, 'min_child_weight': 2, 'gamma': 0.4340533246209475, 'reg_alpha': 0.014228155788417055, 'reg_lambda': 0.3937302381178651, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:47,128] Trial 18 finished with value: 0.5901861390191445 and parameters: {'max_depth': 4, 'learning_rate': 0.015665964662030497, 'n_estimators': 769, 'subsample': 0.7632655703780667, 'colsample_bytree': 0.8702543170646435, 'min_child_weight': 9, 'gamma': 0.3398733712684563, 'reg_alpha': 0.16813411390561703, 'reg_lambda': 1.8336922118036476, 'scale_pos_weight': 1}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:47,901] Trial 19 finished with value: 0.6239349920462887 and parameters: {'max_depth': 3, 'learning_rate': 0.03211232715464467, 'n_estimators': 595, 'subsample': 0.6607076608543617, 'colsample_bytree': 0.7782318457266307, 'min_child_weight': 3, 'gamma': 0.18331010887593435, 'reg_alpha': 0.6098179907114522, 'reg_lambda': 1.2774080718154193, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 5 with value: 0.6284817713670061.
[I 2026-03-06 22:45:48,679] Trial 20 finished with value: 0.6309203756591175 and parameters: {'max_depth': 5, 'learning_rate': 0.01324956452756274, 'n_estimators': 406, 'subsample': 0.7091428627847151, 'colsample_bytree': 0.7357953432037215, 'min_child_weight': 6, 'gamma': 0.2940822860620359, 'reg_alpha': 0.37534987337102227, 'reg_lambda': 0.839272933053633, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:49,458] Trial 21 finished with value: 0.6294519953535311 and parameters: {'max_depth': 5, 'learning_rate': 0.015387842200909514, 'n_estimators': 415, 'subsample': 0.7149403470418026, 'colsample_bytree': 0.740865967908946, 'min_child_weight': 6, 'gamma': 0.28657978756025304, 'reg_alpha': 0.3919177863633243, 'reg_lambda': 0.8521469730204952, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:50,184] Trial 22 finished with value: 0.6265518743102281 and parameters: {'max_depth': 5, 'learning_rate': 0.024825047718063667, 'n_estimators': 390, 'subsample': 0.714819121732648, 'colsample_bytree': 0.7310369973072147, 'min_child_weight': 6, 'gamma': 0.3026220500932805, 'reg_alpha': 0.40738903454030434, 'reg_lambda': 0.7091569314401663, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:51,052] Trial 23 finished with value: 0.626247476015397 and parameters: {'max_depth': 5, 'learning_rate': 0.014336903251054878, 'n_estimators': 409, 'subsample': 0.7550663683300243, 'colsample_bytree': 0.6704647605242618, 'min_child_weight': 8, 'gamma': 0.3956241099770118, 'reg_alpha': 0.38137267162006466, 'reg_lambda': 0.4626532788239809, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:52,128] Trial 24 finished with value: 0.6243687552315929 and parameters: {'max_depth': 4, 'learning_rate': 0.013311679726090738, 'n_estimators': 533, 'subsample': 0.8968021540409487, 'colsample_bytree': 0.747685057336171, 'min_child_weight': 4, 'gamma': 0.29414965247208924, 'reg_alpha': 0.7266717575475339, 'reg_lambda': 0.831296220386417, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:52,800] Trial 25 finished with value: 0.6267167809702268 and parameters: {'max_depth': 3, 'learning_rate': 0.019898115017518245, 'n_estimators': 376, 'subsample': 0.6994924260727743, 'colsample_bytree': 0.673425739787223, 'min_child_weight': 8, 'gamma': 0.4267163097700667, 'reg_alpha': 0.5295334600973767, 'reg_lambda': 1.1960304910484862, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:53,382] Trial 26 finished with value: 0.5831113574520396 and parameters: {'max_depth': 5, 'learning_rate': 0.01306326297688394, 'n_estimators': 240, 'subsample': 0.8199793749295191, 'colsample_bytree': 0.7995518032890404, 'min_child_weight': 6, 'gamma': 0.3438396820393166, 'reg_alpha': 0.34449941657079675, 'reg_lambda': 0.21814948551406543, 'scale_pos_weight': 1}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:54,497] Trial 27 finished with value: 0.6184047956874044 and parameters: {'max_depth': 7, 'learning_rate': 0.01820245116295095, 'n_estimators': 523, 'subsample': 0.7712727432911372, 'colsample_bytree': 0.7382380175138135, 'min_child_weight': 9, 'gamma': 0.23294663278312225, 'reg_alpha': 0.18724394526427132, 'reg_lambda': 1.3894056182276016, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:55,553] Trial 28 finished with value: 0.6127132097858626 and parameters: {'max_depth': 6, 'learning_rate': 0.03175178897672161, 'n_estimators': 429, 'subsample': 0.7328647572370593, 'colsample_bytree': 0.7866682401804472, 'min_child_weight': 5, 'gamma': 0.28928893680158607, 'reg_alpha': 0.5212671797626379, 'reg_lambda': 0.7891813186060721, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:56,270] Trial 29 finished with value: 0.6220271062044076 and parameters: {'max_depth': 3, 'learning_rate': 0.053622155101458756, 'n_estimators': 362, 'subsample': 0.8189715000211658, 'colsample_bytree': 0.6898212364427907, 'min_child_weight': 7, 'gamma': 0.41932716166735867, 'reg_alpha': 0.3312974994019788, 'reg_lambda': 0.519539501727452, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:56,778] Trial 30 finished with value: 0.6261818526734325 and parameters: {'max_depth': 4, 'learning_rate': 0.010014064254860242, 'n_estimators': 218, 'subsample': 0.8820451339457955, 'colsample_bytree': 0.6457462551663222, 'min_child_weight': 4, 'gamma': 0.37158494398916325, 'reg_alpha': 0.23169930756001864, 'reg_lambda': 1.011754278685899, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:57,789] Trial 31 finished with value: 0.6252066611504126 and parameters: {'max_depth': 4, 'learning_rate': 0.013060483012660088, 'n_estimators': 690, 'subsample': 0.6460460262439043, 'colsample_bytree': 0.8327870945379505, 'min_child_weight': 2, 'gamma': 0.13938581151672153, 'reg_alpha': 0.3136699453929627, 'reg_lambda': 0.8835096811174458, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:58,667] Trial 32 finished with value: 0.6238025075872804 and parameters: {'max_depth': 3, 'learning_rate': 0.015565764813579179, 'n_estimators': 613, 'subsample': 0.6777369590587871, 'colsample_bytree': 0.7321631908900956, 'min_child_weight': 6, 'gamma': 0.20765157484217295, 'reg_alpha': 0.11442022362298127, 'reg_lambda': 0.922960334617311, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:45:59,875] Trial 33 finished with value: 0.6191160239802035 and parameters: {'max_depth': 5, 'learning_rate': 0.02314675884290372, 'n_estimators': 698, 'subsample': 0.6384725974263941, 'colsample_bytree': 0.8497901571440668, 'min_child_weight': 7, 'gamma': 0.497966553739262, 'reg_alpha': 0.4642102726243166, 'reg_lambda': 0.5867198003742822, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:00,987] Trial 34 finished with value: 0.629225088583196 and parameters: {'max_depth': 4, 'learning_rate': 0.011912772235793005, 'n_estimators': 787, 'subsample': 0.6025638984937128, 'colsample_bytree': 0.8048028391276578, 'min_child_weight': 5, 'gamma': 0.11738244284613064, 'reg_alpha': 0.15028929460950408, 'reg_lambda': 1.1599142513362817, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:02,513] Trial 35 finished with value: 0.6184261118964551 and parameters: {'max_depth': 6, 'learning_rate': 0.012788866531397805, 'n_estimators': 867, 'subsample': 0.7257735290773694, 'colsample_bytree': 0.7614984429451651, 'min_child_weight': 5, 'gamma': 0.45440697447471906, 'reg_alpha': 0.21163514917783494, 'reg_lambda': 1.3660302823514583, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:03,401] Trial 36 finished with value: 0.6089818273423727 and parameters: {'max_depth': 5, 'learning_rate': 0.04759258778780007, 'n_estimators': 489, 'subsample': 0.6038461347396368, 'colsample_bytree': 0.7980384965010767, 'min_child_weight': 4, 'gamma': 0.09278247234404363, 'reg_alpha': 0.1340848327508419, 'reg_lambda': 1.1243686216097455, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:04,535] Trial 37 finished with value: 0.5794120914339246 and parameters: {'max_depth': 3, 'learning_rate': 0.07557312022125473, 'n_estimators': 942, 'subsample': 0.7968297062722608, 'colsample_bytree': 0.6521944074069848, 'min_child_weight': 5, 'gamma': 0.2009311876817631, 'reg_alpha': 0.3944908287668057, 'reg_lambda': 1.5355327604270674, 'scale_pos_weight': 1}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:05,464] Trial 38 finished with value: 0.6266607571690084 and parameters: {'max_depth': 6, 'learning_rate': 0.017639939998273322, 'n_estimators': 451, 'subsample': 0.6865898708822448, 'colsample_bytree': 0.7171040671294316, 'min_child_weight': 9, 'gamma': 0.007813660191562335, 'reg_alpha': 0.299232728129153, 'reg_lambda': 1.6919280632539477, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:06,312] Trial 39 finished with value: 0.5697879147885241 and parameters: {'max_depth': 4, 'learning_rate': 0.13418970589365986, 'n_estimators': 571, 'subsample': 0.6051060943210657, 'colsample_bytree': 0.916838709656685, 'min_child_weight': 8, 'gamma': 0.24912933899595713, 'reg_alpha': 0.46683860351701734, 'reg_lambda': 0.702047253498185, 'scale_pos_weight': 1}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:07,638] Trial 40 finished with value: 0.6239493617903624 and parameters: {'max_depth': 5, 'learning_rate': 0.011978798749521288, 'n_estimators': 832, 'subsample': 0.7847582020503618, 'colsample_bytree': 0.7618023023846486, 'min_child_weight': 10, 'gamma': 0.31608470746438944, 'reg_alpha': 0.07565452344893889, 'reg_lambda': 1.2380501210980304, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:08,724] Trial 41 finished with value: 0.6237547995165615 and parameters: {'max_depth': 4, 'learning_rate': 0.01659235125015799, 'n_estimators': 785, 'subsample': 0.6577489645233572, 'colsample_bytree': 0.7784780993993018, 'min_child_weight': 2, 'gamma': 0.10923660313874689, 'reg_alpha': 0.056364374253743965, 'reg_lambda': 0.9472856006545988, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.
[I 2026-03-06 22:46:09,685] Trial 42 finished with value: 0.6292889586980923 and parameters: {'max_depth': 4, 'learning_rate': 0.015553629133375674, 'n_estimators': 655, 'subsample': 0.6269591431907915, 'colsample_bytree': 0.8236003480342581, 'min_child_weight': 3, 'gamma': 0.07056132180641042, 'reg_alpha': 0.14375202044273833, 'reg_lambda': 0.7892443039238796, 'scale_pos_weight': np.float64(2.785329744279946)}. Best is trial 20 with value: 0.6309203756591175.

Best params are  {'max_depth': 6, 'learning_rate': 0.022115541143650032, 'n_estimators': 219, 'subsample': 0.6295470144507495, 'colsample_bytree': 0.7718132768896089, 'min_child_weight': 7, 'gamma': 0.32981335098363035, 'reg_alpha': 0.2981902127645493, 'reg_lambda': 0.12235204310395453, 'scale_pos_weight': np.float64(2.785329744279946)}
best score is : 0.6316919246298747
classification_report is
 :                precision    recall  f1-score   support

           0       0.89      0.76      0.82      1024
           1       0.54      0.75      0.63       383

    accuracy                           0.76      1407
   macro avg       0.71      0.75      0.72      1407
weighted avg       0.79      0.76      0.77      1407

In [57]:
joblib.dump(best_optuna_model,'./models/best_optuna_model.pkl')
print("optuna model saved Successfully")

optuna model saved Successfully

In [58]:
joblib.dump(model_ada_weighted,"./models/adaboost_weighted_model.pkl")
print("adaboost weighted model saved Successfully")

adaboost weighted model saved Successfully